// Package messenger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package messenger

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthorizationCodeScopes = "AuthorizationCode.Scopes"
	ClientCredentialsScopes = "ClientCredentials.Scopes"
)

// Defines values for MessageContentCallStatus.
const (
	Missed MessageContentCallStatus = "missed"
)

// Valid indicates whether the value is a known member of the MessageContentCallStatus enum.
func (e MessageContentCallStatus) Valid() bool {
	switch e {
	case Missed:
		return true
	default:
		return false
	}
}

// Defines values for MessageContentLocationKind.
const (
	Area      MessageContentLocationKind = "area"
	DotDotDot MessageContentLocationKind = "..."
	House     MessageContentLocationKind = "house"
	Street    MessageContentLocationKind = "street"
)

// Valid indicates whether the value is a known member of the MessageContentLocationKind enum.
func (e MessageContentLocationKind) Valid() bool {
	switch e {
	case Area:
		return true
	case DotDotDot:
		return true
	case House:
		return true
	case Street:
		return true
	default:
		return false
	}
}

// Defines values for MessageQuoteType.
const (
	MessageQuoteTypeCall     MessageQuoteType = "call"
	MessageQuoteTypeDeleted  MessageQuoteType = "deleted"
	MessageQuoteTypeImage    MessageQuoteType = "image"
	MessageQuoteTypeItem     MessageQuoteType = "item"
	MessageQuoteTypeLink     MessageQuoteType = "link"
	MessageQuoteTypeLocation MessageQuoteType = "location"
	MessageQuoteTypeSystem   MessageQuoteType = "system"
	MessageQuoteTypeText     MessageQuoteType = "text"
	MessageQuoteTypeVoice    MessageQuoteType = "voice"
)

// Valid indicates whether the value is a known member of the MessageQuoteType enum.
func (e MessageQuoteType) Valid() bool {
	switch e {
	case MessageQuoteTypeCall:
		return true
	case MessageQuoteTypeDeleted:
		return true
	case MessageQuoteTypeImage:
		return true
	case MessageQuoteTypeItem:
		return true
	case MessageQuoteTypeLink:
		return true
	case MessageQuoteTypeLocation:
		return true
	case MessageQuoteTypeSystem:
		return true
	case MessageQuoteTypeText:
		return true
	case MessageQuoteTypeVoice:
		return true
	default:
		return false
	}
}

// Defines values for MessagesDirection.
const (
	In  MessagesDirection = "in"
	Out MessagesDirection = "out"
)

// Valid indicates whether the value is a known member of the MessagesDirection enum.
func (e MessagesDirection) Valid() bool {
	switch e {
	case In:
		return true
	case Out:
		return true
	default:
		return false
	}
}

// Defines values for MessagesType.
const (
	MessagesTypeCall     MessagesType = "call"
	MessagesTypeDeleted  MessagesType = "deleted"
	MessagesTypeImage    MessagesType = "image"
	MessagesTypeItem     MessagesType = "item"
	MessagesTypeLink     MessagesType = "link"
	MessagesTypeLocation MessagesType = "location"
	MessagesTypeSystem   MessagesType = "system"
	MessagesTypeText     MessagesType = "text"
	MessagesTypeVoice    MessagesType = "voice"
)

// Valid indicates whether the value is a known member of the MessagesType enum.
func (e MessagesType) Valid() bool {
	switch e {
	case MessagesTypeCall:
		return true
	case MessagesTypeDeleted:
		return true
	case MessagesTypeImage:
		return true
	case MessagesTypeItem:
		return true
	case MessagesTypeLink:
		return true
	case MessagesTypeLocation:
		return true
	case MessagesTypeSystem:
		return true
	case MessagesTypeText:
		return true
	case MessagesTypeVoice:
		return true
	default:
		return false
	}
}

// Defines values for WebhookMessageChatType.
const (
	U2i WebhookMessageChatType = "u2i"
	U2u WebhookMessageChatType = "u2u"
)

// Valid indicates whether the value is a known member of the WebhookMessageChatType enum.
func (e WebhookMessageChatType) Valid() bool {
	switch e {
	case U2i:
		return true
	case U2u:
		return true
	default:
		return false
	}
}

// Defines values for WebhookMessageType.
const (
	WebhookMessageTypeAppCall  WebhookMessageType = "appCall"
	WebhookMessageTypeCall     WebhookMessageType = "call"
	WebhookMessageTypeDeleted  WebhookMessageType = "deleted"
	WebhookMessageTypeFile     WebhookMessageType = "file"
	WebhookMessageTypeImage    WebhookMessageType = "image"
	WebhookMessageTypeItem     WebhookMessageType = "item"
	WebhookMessageTypeLink     WebhookMessageType = "link"
	WebhookMessageTypeLocation WebhookMessageType = "location"
	WebhookMessageTypeSystem   WebhookMessageType = "system"
	WebhookMessageTypeText     WebhookMessageType = "text"
	WebhookMessageTypeVideo    WebhookMessageType = "video"
	WebhookMessageTypeVoice    WebhookMessageType = "voice"
)

// Valid indicates whether the value is a known member of the WebhookMessageType enum.
func (e WebhookMessageType) Valid() bool {
	switch e {
	case WebhookMessageTypeAppCall:
		return true
	case WebhookMessageTypeCall:
		return true
	case WebhookMessageTypeDeleted:
		return true
	case WebhookMessageTypeFile:
		return true
	case WebhookMessageTypeImage:
		return true
	case WebhookMessageTypeItem:
		return true
	case WebhookMessageTypeLink:
		return true
	case WebhookMessageTypeLocation:
		return true
	case WebhookMessageTypeSystem:
		return true
	case WebhookMessageTypeText:
		return true
	case WebhookMessageTypeVideo:
		return true
	case WebhookMessageTypeVoice:
		return true
	default:
		return false
	}
}

// Defines values for AddBlacklistRequestBodyUsersContextReasonId.
const (
	N1 AddBlacklistRequestBodyUsersContextReasonId = 1
	N2 AddBlacklistRequestBodyUsersContextReasonId = 2
	N3 AddBlacklistRequestBodyUsersContextReasonId = 3
	N4 AddBlacklistRequestBodyUsersContextReasonId = 4
)

// Valid indicates whether the value is a known member of the AddBlacklistRequestBodyUsersContextReasonId enum.
func (e AddBlacklistRequestBodyUsersContextReasonId) Valid() bool {
	switch e {
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	case N4:
		return true
	default:
		return false
	}
}

// Defines values for SendMessageRequestBodyType.
const (
	SendMessageRequestBodyTypeText SendMessageRequestBodyType = "text"
)

// Valid indicates whether the value is a known member of the SendMessageRequestBodyType enum.
func (e SendMessageRequestBodyType) Valid() bool {
	switch e {
	case SendMessageRequestBodyTypeText:
		return true
	default:
		return false
	}
}

// Chat defines model for Chat.
type Chat struct {
	// Context Сопутствующая к чату информация, несвязанная с мессенджером напрямую
	Context *struct {
		// Type Тип контекста, определяет значение и смысл других полей в объекте контекста
		Type  *string `json:"type,omitempty"`
		Value *struct {
			// Id ID объявления
			Id *int64 `json:"id,omitempty"`

			// Images Изображения с карточки объявления
			Images *struct {
				// Count Число изображений
				Count *int32 `json:"count,omitempty"`
				Main  *struct {
					// N140x105 Изображение в формате 140х105
					N140x105 *string `json:"140x105,omitempty"`
				} `json:"main,omitempty"`
			} `json:"images,omitempty"`

			// PriceString Цена в объявлении, с указанием валюты
			PriceString *string `json:"price_string,omitempty"`

			// StatusId Статус объявления, например 20 — объявление удалено
			StatusId *int32  `json:"status_id,omitempty"`
			Title    *string `json:"title,omitempty"`

			// Url Ссылка на объявление
			Url *string `json:"url,omitempty"`

			// UserId ID автора объявления
			UserId *int32 `json:"user_id,omitempty"`
		} `json:"value,omitempty"`
	} `json:"context,omitempty"`

	// Created Unix-timestamp времени создания чата
	Created *int32 `json:"created,omitempty"`

	// Id Уникальный идентификтор чата
	Id          *string `json:"id,omitempty"`
	LastMessage *struct {
		// AuthorId Ссылка на профиль пользователя в Авито
		AuthorId *int32 `json:"author_id,omitempty"`

		// Content Для сообщений типов "appCall" "file" "video" возвращается empty object (данные типы не поддерживаются)
		Content *MessageContent `json:"content,omitempty"`

		// Created Unix-timestamp времени отправки сообщения
		Created *int32 `json:"created,omitempty"`

		// Direction "in" для входящих сообщений, "out" для исходящих
		Direction *string `json:"direction,omitempty"`

		// Id Уникальный идентификатор сообщения
		Id *string `json:"id,omitempty"`

		// Type Тип контента в сообщений
		Type *string `json:"type,omitempty"`
	} `json:"last_message,omitempty"`

	// Updated Unix-timestamp времени последнего обновления чата
	Updated *int32 `json:"updated,omitempty"`
	Users   *[]struct {
		// Id Уникальный ID пользователя. Обратите внимание на хэширование
		Id *int32 `json:"id,omitempty"`

		// Name Имя пользователя
		Name              *string `json:"name,omitempty"`
		PublicUserProfile *struct {
			// Avatar Фотография пользователя (аватар)
			Avatar *struct {
				Default *string `json:"default,omitempty"`
				Images  *struct {
					// N128x128 Аватар в формате 128х128
					N128x128 *string `json:"128x128,omitempty"`

					// N192x192 Аватар в формате 192х192
					N192x192 *string `json:"192x192,omitempty"`

					// N24x24 Аватар в формате 24х24
					N24x24 *string `json:"24x24,omitempty"`

					// N256x256 Аватар в формате 256х256
					N256x256 *string `json:"256x256,omitempty"`

					// N36x36 Аватар в формате 36х36
					N36x36 *string `json:"36x36,omitempty"`

					// N48x48 Аватар в формате 48х48
					N48x48 *string `json:"48x48,omitempty"`

					// N64x64 Аватар в формате 64х64
					N64x64 *string `json:"64x64,omitempty"`

					// N72x72 Аватар в формате 72х72
					N72x72 *string `json:"72x72,omitempty"`

					// N96x96 Аватар в формате 96х96
					N96x96 *string `json:"96x96,omitempty"`
				} `json:"images,omitempty"`
			} `json:"avatar,omitempty"`

			// ItemId ID объявления, выложенного пользователем
			ItemId *int64 `json:"item_id,omitempty"`

			// Url Ссылка на профиль пользователя в Авито
			Url *string `json:"url,omitempty"`

			// UserId Уникальный ID пользователя. Обратите внимание на хэширование
			UserId *int32 `json:"user_id,omitempty"`
		} `json:"public_user_profile,omitempty"`
	} `json:"users,omitempty"`
}

// Chats defines model for Chats.
type Chats struct {
	// Chats Список чатов
	Chats *[]Chat `json:"chats,omitempty"`
}

// MessageContent Для сообщений типов "appCall" "file" "video" возвращается empty object (данные типы не поддерживаются)
type MessageContent struct {
	// Call Объект, описывающий звонок, для сообщения типа call
	Call *struct {
		Status       *MessageContentCallStatus `json:"status,omitempty"`
		TargetUserId *int64                    `json:"target_user_id,omitempty"`
	} `json:"call,omitempty"`

	// FlowId Идентификатор чат-бота, отправившего сообщение, для сообщений типа system
	FlowId *string `json:"flow_id,omitempty"`

	// Image Объект, описывающий изображение, для сообщения типа image
	Image *struct {
		// Sizes объект ключ-значение, где ключи - строки в формате "ШxВ" (ширина, высота), а значения - ссылки на изображения
		Sizes *map[string]interface{} `json:"sizes,omitempty"`
	} `json:"image,omitempty"`

	// Item Объект, описывающий объявление, для сообщения типа item
	Item *struct {
		ImageUrl    *string `json:"image_url,omitempty"`
		ItemUrl     *string `json:"item_url,omitempty"`
		PriceString *string `json:"price_string,omitempty"`
		Title       *string `json:"title,omitempty"`
	} `json:"item,omitempty"`

	// Link Объект, описывающий ссылку, для сообщения типа link
	Link *struct {
		Preview *struct {
			Description *string `json:"description,omitempty"`
			Domain      *string `json:"domain,omitempty"`

			// Images объект ключ-значение, где ключи - строки в формате "ШxВ" (ширина, высота), а значения - ссылки на изображения
			Images *map[string]interface{} `json:"images,omitempty"`
			Title  *string                 `json:"title,omitempty"`
			Url    *string                 `json:"url,omitempty"`
		} `json:"preview,omitempty"`
		Text *string `json:"text,omitempty"`
		Url  *string `json:"url,omitempty"`
	} `json:"link,omitempty"`

	// Location Объект, описывающий геометку, для сообщения типа location
	Location *struct {
		Kind  *MessageContentLocationKind `json:"kind,omitempty"`
		Lat   *float32                    `json:"lat,omitempty"`
		Lon   *float32                    `json:"lon,omitempty"`
		Text  *string                     `json:"text,omitempty"`
		Title *string                     `json:"title,omitempty"`
	} `json:"location,omitempty"`

	// Text Текст сообщения, для сообщения типа text
	Text *string `json:"text,omitempty"`

	// Voice Объект, описывающий голосовое сообщение, для сообщения типа voice
	Voice *struct {
		VoiceId *string `json:"voice_id,omitempty"`
	} `json:"voice,omitempty"`
}

// MessageContentCallStatus defines model for MessageContent.Call.Status.
type MessageContentCallStatus string

// MessageContentLocationKind defines model for MessageContent.Location.Kind.
type MessageContentLocationKind string

// MessageQuote цитируемое сообщение
type MessageQuote struct {
	AuthorId *int64 `json:"author_id,omitempty"`

	// Content Для сообщений типов "appCall" "file" "video" возвращается empty object (данные типы не поддерживаются)
	Content *MessageContent   `json:"content,omitempty"`
	Created *int64            `json:"created,omitempty"`
	Id      *string           `json:"id,omitempty"`
	Type    *MessageQuoteType `json:"type,omitempty"`
}

// MessageQuoteType defines model for MessageQuote.Type.
type MessageQuoteType string

// Messages defines model for Messages.
type Messages = []struct {
	AuthorId *int64 `json:"author_id,omitempty"`

	// Content Для сообщений типов "appCall" "file" "video" возвращается empty object (данные типы не поддерживаются)
	Content   *MessageContent    `json:"content,omitempty"`
	Created   *int64             `json:"created,omitempty"`
	Direction *MessagesDirection `json:"direction,omitempty"`
	Id        *string            `json:"id,omitempty"`

	// IsRead True, если сообщение уже было прочитано запрашиваемым пользователем. Иначе false
	IsRead *bool `json:"is_read,omitempty"`

	// Quote цитируемое сообщение
	Quote *MessageQuote `json:"quote,omitempty"`

	// Read Unix-timestamp времени, когда сообщение было прочитано собеседником
	Read *int          `json:"read,omitempty"`
	Type *MessagesType `json:"type,omitempty"`
}

// MessagesDirection defines model for Messages.Direction.
type MessagesDirection string

// MessagesType defines model for Messages.Type.
type MessagesType string

// PayloadStruct defines model for PayloadStruct.
type PayloadStruct struct {
	// Type Тип сообщения
	Type  *string         `json:"type,omitempty"`
	Value *WebhookMessage `json:"value,omitempty"`
}

// VoiceFiles defines model for VoiceFiles.
type VoiceFiles struct {
	VoicesUrls *map[string]string `json:"voices_urls,omitempty"`
}

// WebhookMessage defines model for WebhookMessage.
type WebhookMessage struct {
	// AuthorId ID пользователя, отправившего сообщение
	AuthorId *int `json:"author_id,omitempty"`

	// ChatId Уникальный идентификатор чата, куда отправлено сообщение
	ChatId *string `json:"chat_id,omitempty"`

	// ChatType Тип чата (u2i - чат по объявлению, u2u - чат по профилю пользователя)
	ChatType *WebhookMessageChatType `json:"chat_type,omitempty"`

	// Content Для сообщений типов "appCall" "file" "video" возвращается empty object (данные типы не поддерживаются)
	Content *MessageContent `json:"content,omitempty"`

	// Created Unix-timestamp времени создания сообщения
	Created *int `json:"created,omitempty"`

	// Id Уникальный идентификатор сообщения
	Id *string `json:"id,omitempty"`

	// ItemId ID объявления, актуально только для чатов с типом u2i
	ItemId *int `json:"item_id,omitempty"`

	// PublishedAt Время публикации сообщения в формате RFC3339 в UTC
	PublishedAt *string `json:"published_at,omitempty"`

	// Read Unix-timestamp времени прочтения, если сообщение уже прочитано
	Read *int `json:"read,omitempty"`

	// Type Тип сообщения
	Type *WebhookMessageType `json:"type,omitempty"`

	// UserId ID пользователя, получившего сообщение. Это всегда аккаунт, на который зарегистрирован вебхук
	UserId *int `json:"user_id,omitempty"`
}

// WebhookMessageChatType Тип чата (u2i - чат по объявлению, u2u - чат по профилю пользователя)
type WebhookMessageChatType string

// WebhookMessageType Тип сообщения
type WebhookMessageType string

// AddBlacklistRequestBody defines model for addBlacklistRequestBody.
type AddBlacklistRequestBody struct {
	Users *[]struct {
		Context *struct {
			ItemId *int64 `json:"item_id,omitempty"`

			// ReasonId причина, по которой блокируем пользователя, 1 - спам, 2 - мошенничество, 3 - оскорбления и хамство, 4 - другая причина
			ReasonId *AddBlacklistRequestBodyUsersContextReasonId `json:"reason_id,omitempty"`
		} `json:"context,omitempty"`

		// UserId id пользователя которого хотим заблокировать
		UserId *int64 `json:"user_id,omitempty"`
	} `json:"users,omitempty"`
}

// AddBlacklistRequestBodyUsersContextReasonId причина, по которой блокируем пользователя, 1 - спам, 2 - мошенничество, 3 - оскорбления и хамство, 4 - другая причина
type AddBlacklistRequestBodyUsersContextReasonId int

// SendImageMessageRequestBody defines model for sendImageMessageRequestBody.
type SendImageMessageRequestBody struct {
	// ImageId Идентификатор загруженного изображения
	ImageId string `json:"image_id"`
}

// SendMessageRequestBody defines model for sendMessageRequestBody.
type SendMessageRequestBody struct {
	Message *struct {
		// Text Текст сообщения (максимум 1000 символов)
		Text *string `json:"text,omitempty"`
	} `json:"message,omitempty"`

	// Type Тип сообщения
	Type *SendMessageRequestBodyType `json:"type,omitempty"`
}

// SendMessageRequestBodyType Тип сообщения
type SendMessageRequestBodyType string

// WebhookSubscribeRequestBody defines model for webhookSubscribeRequestBody.
type WebhookSubscribeRequestBody struct {
	// Url Url на который будут отправляться нотификации
	Url string `json:"url"`
}

// AuthHeader defines model for authHeader.
type AuthHeader = string

// ChatId defines model for chatId.
type ChatId = string

// ChatTypes defines model for chatTypes.
type ChatTypes = []string

// ItemIds defines model for itemIds.
type ItemIds = []int64

// Limit defines model for limit.
type Limit = int32

// MessageId defines model for messageId.
type MessageId = string

// Offset defines model for offset.
type Offset = int32

// UnreadOnly defines model for unreadOnly.
type UnreadOnly = bool

// UserId defines model for userId.
type UserId = int64

// VoiceIds defines model for voiceIds.
type VoiceIds = []string

// PostSendMessageParams defines parameters for PostSendMessage.
type PostSendMessageParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// PostSendImageMessageParams defines parameters for PostSendImageMessage.
type PostSendImageMessageParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// DeleteMessageParams defines parameters for DeleteMessage.
type DeleteMessageParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// ChatReadParams defines parameters for ChatRead.
type ChatReadParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// GetVoiceFilesParams defines parameters for GetVoiceFiles.
type GetVoiceFilesParams struct {
	// VoiceIds Получение файлов голосовых сообщений с указанными voice_id
	VoiceIds VoiceIds `form:"voice_ids" json:"voice_ids"`

	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// UploadImagesMultipartBody defines parameters for UploadImages.
type UploadImagesMultipartBody struct {
	Uploadfile openapi_types.File `json:"uploadfile[]"`
}

// UploadImagesParams defines parameters for UploadImages.
type UploadImagesParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// GetSubscriptionsParams defines parameters for GetSubscriptions.
type GetSubscriptionsParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// PostWebhookUnsubscribeParams defines parameters for PostWebhookUnsubscribe.
type PostWebhookUnsubscribeParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// PostBlacklistV2Params defines parameters for PostBlacklistV2.
type PostBlacklistV2Params struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// GetChatsV2Params defines parameters for GetChatsV2.
type GetChatsV2Params struct {
	// ItemIds Получение чатов только по объявлениям с указанными item_id
	ItemIds *ItemIds `form:"item_ids,omitempty" json:"item_ids,omitempty"`

	// UnreadOnly При значении true метод возвращает только непрочитанные чаты
	UnreadOnly *UnreadOnly `form:"unread_only,omitempty" json:"unread_only,omitempty"`

	// ChatTypes Фильтрация возвращаемых чатов.
	// * u2i — чаты по объявлениям;
	// * u2u — чаты между пользователями;
	ChatTypes *ChatTypes `form:"chat_types,omitempty" json:"chat_types,omitempty"`

	// Limit Количество сообщений / чатов для запроса
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Сдвиг сообщений / чатов для запроса
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// GetChatByIdV2Params defines parameters for GetChatByIdV2.
type GetChatByIdV2Params struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// GetMessagesV3Params defines parameters for GetMessagesV3.
type GetMessagesV3Params struct {
	// Limit Количество сообщений / чатов для запроса
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Сдвиг сообщений / чатов для запроса
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// PostWebhookV3Params defines parameters for PostWebhookV3.
type PostWebhookV3Params struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// PostSendMessageJSONRequestBody defines body for PostSendMessage for application/json ContentType.
type PostSendMessageJSONRequestBody = SendMessageRequestBody

// PostSendImageMessageJSONRequestBody defines body for PostSendImageMessage for application/json ContentType.
type PostSendImageMessageJSONRequestBody = SendImageMessageRequestBody

// UploadImagesMultipartRequestBody defines body for UploadImages for multipart/form-data ContentType.
type UploadImagesMultipartRequestBody UploadImagesMultipartBody

// PostWebhookUnsubscribeJSONRequestBody defines body for PostWebhookUnsubscribe for application/json ContentType.
type PostWebhookUnsubscribeJSONRequestBody = WebhookSubscribeRequestBody

// PostBlacklistV2JSONRequestBody defines body for PostBlacklistV2 for application/json ContentType.
type PostBlacklistV2JSONRequestBody = AddBlacklistRequestBody

// PostWebhookV3JSONRequestBody defines body for PostWebhookV3 for application/json ContentType.
type PostWebhookV3JSONRequestBody = WebhookSubscribeRequestBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostSendMessageWithBody request with any body
	PostSendMessageWithBody(ctx context.Context, userId UserId, chatId ChatId, params *PostSendMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSendMessage(ctx context.Context, userId UserId, chatId ChatId, params *PostSendMessageParams, body PostSendMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSendImageMessageWithBody request with any body
	PostSendImageMessageWithBody(ctx context.Context, userId UserId, chatId ChatId, params *PostSendImageMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSendImageMessage(ctx context.Context, userId UserId, chatId ChatId, params *PostSendImageMessageParams, body PostSendImageMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteMessage request
	DeleteMessage(ctx context.Context, userId UserId, chatId ChatId, messageId MessageId, params *DeleteMessageParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ChatRead request
	ChatRead(ctx context.Context, userId UserId, chatId ChatId, params *ChatReadParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVoiceFiles request
	GetVoiceFiles(ctx context.Context, userId UserId, params *GetVoiceFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadImagesWithBody request with any body
	UploadImagesWithBody(ctx context.Context, userId UserId, params *UploadImagesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSubscriptions request
	GetSubscriptions(ctx context.Context, params *GetSubscriptionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostWebhookUnsubscribeWithBody request with any body
	PostWebhookUnsubscribeWithBody(ctx context.Context, params *PostWebhookUnsubscribeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostWebhookUnsubscribe(ctx context.Context, params *PostWebhookUnsubscribeParams, body PostWebhookUnsubscribeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostBlacklistV2WithBody request with any body
	PostBlacklistV2WithBody(ctx context.Context, userId UserId, params *PostBlacklistV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostBlacklistV2(ctx context.Context, userId UserId, params *PostBlacklistV2Params, body PostBlacklistV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChatsV2 request
	GetChatsV2(ctx context.Context, userId UserId, params *GetChatsV2Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChatByIdV2 request
	GetChatByIdV2(ctx context.Context, userId UserId, chatId ChatId, params *GetChatByIdV2Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMessagesV3 request
	GetMessagesV3(ctx context.Context, userId UserId, chatId ChatId, params *GetMessagesV3Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostWebhookV3WithBody request with any body
	PostWebhookV3WithBody(ctx context.Context, params *PostWebhookV3Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostWebhookV3(ctx context.Context, params *PostWebhookV3Params, body PostWebhookV3JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostSendMessageWithBody(ctx context.Context, userId UserId, chatId ChatId, params *PostSendMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSendMessageRequestWithBody(c.Server, userId, chatId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSendMessage(ctx context.Context, userId UserId, chatId ChatId, params *PostSendMessageParams, body PostSendMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSendMessageRequest(c.Server, userId, chatId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSendImageMessageWithBody(ctx context.Context, userId UserId, chatId ChatId, params *PostSendImageMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSendImageMessageRequestWithBody(c.Server, userId, chatId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSendImageMessage(ctx context.Context, userId UserId, chatId ChatId, params *PostSendImageMessageParams, body PostSendImageMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSendImageMessageRequest(c.Server, userId, chatId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteMessage(ctx context.Context, userId UserId, chatId ChatId, messageId MessageId, params *DeleteMessageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteMessageRequest(c.Server, userId, chatId, messageId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChatRead(ctx context.Context, userId UserId, chatId ChatId, params *ChatReadParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChatReadRequest(c.Server, userId, chatId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVoiceFiles(ctx context.Context, userId UserId, params *GetVoiceFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVoiceFilesRequest(c.Server, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadImagesWithBody(ctx context.Context, userId UserId, params *UploadImagesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadImagesRequestWithBody(c.Server, userId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSubscriptions(ctx context.Context, params *GetSubscriptionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSubscriptionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWebhookUnsubscribeWithBody(ctx context.Context, params *PostWebhookUnsubscribeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWebhookUnsubscribeRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWebhookUnsubscribe(ctx context.Context, params *PostWebhookUnsubscribeParams, body PostWebhookUnsubscribeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWebhookUnsubscribeRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBlacklistV2WithBody(ctx context.Context, userId UserId, params *PostBlacklistV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBlacklistV2RequestWithBody(c.Server, userId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBlacklistV2(ctx context.Context, userId UserId, params *PostBlacklistV2Params, body PostBlacklistV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBlacklistV2Request(c.Server, userId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChatsV2(ctx context.Context, userId UserId, params *GetChatsV2Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChatsV2Request(c.Server, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChatByIdV2(ctx context.Context, userId UserId, chatId ChatId, params *GetChatByIdV2Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChatByIdV2Request(c.Server, userId, chatId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMessagesV3(ctx context.Context, userId UserId, chatId ChatId, params *GetMessagesV3Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMessagesV3Request(c.Server, userId, chatId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWebhookV3WithBody(ctx context.Context, params *PostWebhookV3Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWebhookV3RequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWebhookV3(ctx context.Context, params *PostWebhookV3Params, body PostWebhookV3JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWebhookV3Request(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostSendMessageRequest calls the generic PostSendMessage builder with application/json body
func NewPostSendMessageRequest(server string, userId UserId, chatId ChatId, params *PostSendMessageParams, body PostSendMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSendMessageRequestWithBody(server, userId, chatId, params, "application/json", bodyReader)
}

// NewPostSendMessageRequestWithBody generates requests for PostSendMessage with any type of body
func NewPostSendMessageRequestWithBody(server string, userId UserId, chatId ChatId, params *PostSendMessageParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "chat_id", chatId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v1/accounts/%s/chats/%s/messages", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostSendImageMessageRequest calls the generic PostSendImageMessage builder with application/json body
func NewPostSendImageMessageRequest(server string, userId UserId, chatId ChatId, params *PostSendImageMessageParams, body PostSendImageMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSendImageMessageRequestWithBody(server, userId, chatId, params, "application/json", bodyReader)
}

// NewPostSendImageMessageRequestWithBody generates requests for PostSendImageMessage with any type of body
func NewPostSendImageMessageRequestWithBody(server string, userId UserId, chatId ChatId, params *PostSendImageMessageParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "chat_id", chatId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v1/accounts/%s/chats/%s/messages/image", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewDeleteMessageRequest generates requests for DeleteMessage
func NewDeleteMessageRequest(server string, userId UserId, chatId ChatId, messageId MessageId, params *DeleteMessageParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "chat_id", chatId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "message_id", messageId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v1/accounts/%s/chats/%s/messages/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewChatReadRequest generates requests for ChatRead
func NewChatReadRequest(server string, userId UserId, chatId ChatId, params *ChatReadParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "chat_id", chatId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v1/accounts/%s/chats/%s/read", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetVoiceFilesRequest generates requests for GetVoiceFiles
func NewGetVoiceFilesRequest(server string, userId UserId, params *GetVoiceFilesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v1/accounts/%s/getVoiceFiles", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.VoiceIds != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "voice_ids", params.VoiceIds, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewUploadImagesRequestWithBody generates requests for UploadImages with any type of body
func NewUploadImagesRequestWithBody(server string, userId UserId, params *UploadImagesParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v1/accounts/%s/uploadImages", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetSubscriptionsRequest generates requests for GetSubscriptions
func NewGetSubscriptionsRequest(server string, params *GetSubscriptionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v1/subscriptions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostWebhookUnsubscribeRequest calls the generic PostWebhookUnsubscribe builder with application/json body
func NewPostWebhookUnsubscribeRequest(server string, params *PostWebhookUnsubscribeParams, body PostWebhookUnsubscribeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostWebhookUnsubscribeRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostWebhookUnsubscribeRequestWithBody generates requests for PostWebhookUnsubscribe with any type of body
func NewPostWebhookUnsubscribeRequestWithBody(server string, params *PostWebhookUnsubscribeParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v1/webhook/unsubscribe")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostBlacklistV2Request calls the generic PostBlacklistV2 builder with application/json body
func NewPostBlacklistV2Request(server string, userId UserId, params *PostBlacklistV2Params, body PostBlacklistV2JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostBlacklistV2RequestWithBody(server, userId, params, "application/json", bodyReader)
}

// NewPostBlacklistV2RequestWithBody generates requests for PostBlacklistV2 with any type of body
func NewPostBlacklistV2RequestWithBody(server string, userId UserId, params *PostBlacklistV2Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v2/accounts/%s/blacklist", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetChatsV2Request generates requests for GetChatsV2
func NewGetChatsV2Request(server string, userId UserId, params *GetChatsV2Params) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v2/accounts/%s/chats", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ItemIds != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "item_ids", *params.ItemIds, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.UnreadOnly != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "unread_only", *params.UnreadOnly, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ChatTypes != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "chat_types", *params.ChatTypes, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetChatByIdV2Request generates requests for GetChatByIdV2
func NewGetChatByIdV2Request(server string, userId UserId, chatId ChatId, params *GetChatByIdV2Params) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "chat_id", chatId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v2/accounts/%s/chats/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetMessagesV3Request generates requests for GetMessagesV3
func NewGetMessagesV3Request(server string, userId UserId, chatId ChatId, params *GetMessagesV3Params) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "chat_id", chatId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v3/accounts/%s/chats/%s/messages/", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostWebhookV3Request calls the generic PostWebhookV3 builder with application/json body
func NewPostWebhookV3Request(server string, params *PostWebhookV3Params, body PostWebhookV3JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostWebhookV3RequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostWebhookV3RequestWithBody generates requests for PostWebhookV3 with any type of body
func NewPostWebhookV3RequestWithBody(server string, params *PostWebhookV3Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messenger/v3/webhook")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostSendMessageWithBodyWithResponse request with any body
	PostSendMessageWithBodyWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *PostSendMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSendMessageResponse, error)

	PostSendMessageWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *PostSendMessageParams, body PostSendMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSendMessageResponse, error)

	// PostSendImageMessageWithBodyWithResponse request with any body
	PostSendImageMessageWithBodyWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *PostSendImageMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSendImageMessageResponse, error)

	PostSendImageMessageWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *PostSendImageMessageParams, body PostSendImageMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSendImageMessageResponse, error)

	// DeleteMessageWithResponse request
	DeleteMessageWithResponse(ctx context.Context, userId UserId, chatId ChatId, messageId MessageId, params *DeleteMessageParams, reqEditors ...RequestEditorFn) (*DeleteMessageResponse, error)

	// ChatReadWithResponse request
	ChatReadWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *ChatReadParams, reqEditors ...RequestEditorFn) (*ChatReadResponse, error)

	// GetVoiceFilesWithResponse request
	GetVoiceFilesWithResponse(ctx context.Context, userId UserId, params *GetVoiceFilesParams, reqEditors ...RequestEditorFn) (*GetVoiceFilesResponse, error)

	// UploadImagesWithBodyWithResponse request with any body
	UploadImagesWithBodyWithResponse(ctx context.Context, userId UserId, params *UploadImagesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadImagesResponse, error)

	// GetSubscriptionsWithResponse request
	GetSubscriptionsWithResponse(ctx context.Context, params *GetSubscriptionsParams, reqEditors ...RequestEditorFn) (*GetSubscriptionsResponse, error)

	// PostWebhookUnsubscribeWithBodyWithResponse request with any body
	PostWebhookUnsubscribeWithBodyWithResponse(ctx context.Context, params *PostWebhookUnsubscribeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWebhookUnsubscribeResponse, error)

	PostWebhookUnsubscribeWithResponse(ctx context.Context, params *PostWebhookUnsubscribeParams, body PostWebhookUnsubscribeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostWebhookUnsubscribeResponse, error)

	// PostBlacklistV2WithBodyWithResponse request with any body
	PostBlacklistV2WithBodyWithResponse(ctx context.Context, userId UserId, params *PostBlacklistV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBlacklistV2Response, error)

	PostBlacklistV2WithResponse(ctx context.Context, userId UserId, params *PostBlacklistV2Params, body PostBlacklistV2JSONRequestBody, reqEditors ...RequestEditorFn) (*PostBlacklistV2Response, error)

	// GetChatsV2WithResponse request
	GetChatsV2WithResponse(ctx context.Context, userId UserId, params *GetChatsV2Params, reqEditors ...RequestEditorFn) (*GetChatsV2Response, error)

	// GetChatByIdV2WithResponse request
	GetChatByIdV2WithResponse(ctx context.Context, userId UserId, chatId ChatId, params *GetChatByIdV2Params, reqEditors ...RequestEditorFn) (*GetChatByIdV2Response, error)

	// GetMessagesV3WithResponse request
	GetMessagesV3WithResponse(ctx context.Context, userId UserId, chatId ChatId, params *GetMessagesV3Params, reqEditors ...RequestEditorFn) (*GetMessagesV3Response, error)

	// PostWebhookV3WithBodyWithResponse request with any body
	PostWebhookV3WithBodyWithResponse(ctx context.Context, params *PostWebhookV3Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWebhookV3Response, error)

	PostWebhookV3WithResponse(ctx context.Context, params *PostWebhookV3Params, body PostWebhookV3JSONRequestBody, reqEditors ...RequestEditorFn) (*PostWebhookV3Response, error)
}

type PostSendMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Content *struct {
			Text *string `json:"text,omitempty"`
		} `json:"content,omitempty"`
		Created   *int    `json:"created,omitempty"`
		Direction *string `json:"direction,omitempty"`
		Id        *string `json:"id,omitempty"`
		Type      *string `json:"type,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostSendMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSendMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSendImageMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		AuthorId *int `json:"author_id,omitempty"`
		Content  *struct {
			Image *struct {
				Sizes *map[string]string `json:"sizes,omitempty"`
			} `json:"image,omitempty"`
		} `json:"content,omitempty"`
		Created   *int    `json:"created,omitempty"`
		Direction *string `json:"direction,omitempty"`
		Id        *string `json:"id,omitempty"`
		Type      *string `json:"type,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostSendImageMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSendImageMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r DeleteMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ChatReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok *bool `json:"ok,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ChatReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChatReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVoiceFilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VoiceFiles
}

// Status returns HTTPResponse.Status
func (r GetVoiceFilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVoiceFilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]map[string]string
}

// Status returns HTTPResponse.Status
func (r UploadImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSubscriptionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Subscriptions []struct {
			Url string `json:"url"`

			// Version Версия метода, через который вебхук добавлен. Влияет на формат получаемых данных
			Version string `json:"version"`
		} `json:"subscriptions"`
	}
}

// Status returns HTTPResponse.Status
func (r GetSubscriptionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSubscriptionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostWebhookUnsubscribeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok *bool `json:"ok,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostWebhookUnsubscribeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostWebhookUnsubscribeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostBlacklistV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostBlacklistV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostBlacklistV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChatsV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Chats
}

// Status returns HTTPResponse.Status
func (r GetChatsV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChatsV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChatByIdV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Chat
}

// Status returns HTTPResponse.Status
func (r GetChatByIdV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChatByIdV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMessagesV3Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Messages
}

// Status returns HTTPResponse.Status
func (r GetMessagesV3Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMessagesV3Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostWebhookV3Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok *bool `json:"ok,omitempty"`
	}
	JSON201 *struct {
		// Id Уникальный идентификатор сообщения webhooks
		Id      *string        `json:"id,omitempty"`
		Payload *PayloadStruct `json:"payload,omitempty"`

		// Timestamp Unix-timestamp времени отправки сообщения webhooks
		Timestamp *int `json:"timestamp,omitempty"`

		// Version Версия webhooks
		Version *string `json:"version,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostWebhookV3Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostWebhookV3Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostSendMessageWithBodyWithResponse request with arbitrary body returning *PostSendMessageResponse
func (c *ClientWithResponses) PostSendMessageWithBodyWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *PostSendMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSendMessageResponse, error) {
	rsp, err := c.PostSendMessageWithBody(ctx, userId, chatId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSendMessageResponse(rsp)
}

func (c *ClientWithResponses) PostSendMessageWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *PostSendMessageParams, body PostSendMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSendMessageResponse, error) {
	rsp, err := c.PostSendMessage(ctx, userId, chatId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSendMessageResponse(rsp)
}

// PostSendImageMessageWithBodyWithResponse request with arbitrary body returning *PostSendImageMessageResponse
func (c *ClientWithResponses) PostSendImageMessageWithBodyWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *PostSendImageMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSendImageMessageResponse, error) {
	rsp, err := c.PostSendImageMessageWithBody(ctx, userId, chatId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSendImageMessageResponse(rsp)
}

func (c *ClientWithResponses) PostSendImageMessageWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *PostSendImageMessageParams, body PostSendImageMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSendImageMessageResponse, error) {
	rsp, err := c.PostSendImageMessage(ctx, userId, chatId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSendImageMessageResponse(rsp)
}

// DeleteMessageWithResponse request returning *DeleteMessageResponse
func (c *ClientWithResponses) DeleteMessageWithResponse(ctx context.Context, userId UserId, chatId ChatId, messageId MessageId, params *DeleteMessageParams, reqEditors ...RequestEditorFn) (*DeleteMessageResponse, error) {
	rsp, err := c.DeleteMessage(ctx, userId, chatId, messageId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteMessageResponse(rsp)
}

// ChatReadWithResponse request returning *ChatReadResponse
func (c *ClientWithResponses) ChatReadWithResponse(ctx context.Context, userId UserId, chatId ChatId, params *ChatReadParams, reqEditors ...RequestEditorFn) (*ChatReadResponse, error) {
	rsp, err := c.ChatRead(ctx, userId, chatId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChatReadResponse(rsp)
}

// GetVoiceFilesWithResponse request returning *GetVoiceFilesResponse
func (c *ClientWithResponses) GetVoiceFilesWithResponse(ctx context.Context, userId UserId, params *GetVoiceFilesParams, reqEditors ...RequestEditorFn) (*GetVoiceFilesResponse, error) {
	rsp, err := c.GetVoiceFiles(ctx, userId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVoiceFilesResponse(rsp)
}

// UploadImagesWithBodyWithResponse request with arbitrary body returning *UploadImagesResponse
func (c *ClientWithResponses) UploadImagesWithBodyWithResponse(ctx context.Context, userId UserId, params *UploadImagesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadImagesResponse, error) {
	rsp, err := c.UploadImagesWithBody(ctx, userId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadImagesResponse(rsp)
}

// GetSubscriptionsWithResponse request returning *GetSubscriptionsResponse
func (c *ClientWithResponses) GetSubscriptionsWithResponse(ctx context.Context, params *GetSubscriptionsParams, reqEditors ...RequestEditorFn) (*GetSubscriptionsResponse, error) {
	rsp, err := c.GetSubscriptions(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSubscriptionsResponse(rsp)
}

// PostWebhookUnsubscribeWithBodyWithResponse request with arbitrary body returning *PostWebhookUnsubscribeResponse
func (c *ClientWithResponses) PostWebhookUnsubscribeWithBodyWithResponse(ctx context.Context, params *PostWebhookUnsubscribeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWebhookUnsubscribeResponse, error) {
	rsp, err := c.PostWebhookUnsubscribeWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWebhookUnsubscribeResponse(rsp)
}

func (c *ClientWithResponses) PostWebhookUnsubscribeWithResponse(ctx context.Context, params *PostWebhookUnsubscribeParams, body PostWebhookUnsubscribeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostWebhookUnsubscribeResponse, error) {
	rsp, err := c.PostWebhookUnsubscribe(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWebhookUnsubscribeResponse(rsp)
}

// PostBlacklistV2WithBodyWithResponse request with arbitrary body returning *PostBlacklistV2Response
func (c *ClientWithResponses) PostBlacklistV2WithBodyWithResponse(ctx context.Context, userId UserId, params *PostBlacklistV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBlacklistV2Response, error) {
	rsp, err := c.PostBlacklistV2WithBody(ctx, userId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBlacklistV2Response(rsp)
}

func (c *ClientWithResponses) PostBlacklistV2WithResponse(ctx context.Context, userId UserId, params *PostBlacklistV2Params, body PostBlacklistV2JSONRequestBody, reqEditors ...RequestEditorFn) (*PostBlacklistV2Response, error) {
	rsp, err := c.PostBlacklistV2(ctx, userId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBlacklistV2Response(rsp)
}

// GetChatsV2WithResponse request returning *GetChatsV2Response
func (c *ClientWithResponses) GetChatsV2WithResponse(ctx context.Context, userId UserId, params *GetChatsV2Params, reqEditors ...RequestEditorFn) (*GetChatsV2Response, error) {
	rsp, err := c.GetChatsV2(ctx, userId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChatsV2Response(rsp)
}

// GetChatByIdV2WithResponse request returning *GetChatByIdV2Response
func (c *ClientWithResponses) GetChatByIdV2WithResponse(ctx context.Context, userId UserId, chatId ChatId, params *GetChatByIdV2Params, reqEditors ...RequestEditorFn) (*GetChatByIdV2Response, error) {
	rsp, err := c.GetChatByIdV2(ctx, userId, chatId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChatByIdV2Response(rsp)
}

// GetMessagesV3WithResponse request returning *GetMessagesV3Response
func (c *ClientWithResponses) GetMessagesV3WithResponse(ctx context.Context, userId UserId, chatId ChatId, params *GetMessagesV3Params, reqEditors ...RequestEditorFn) (*GetMessagesV3Response, error) {
	rsp, err := c.GetMessagesV3(ctx, userId, chatId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMessagesV3Response(rsp)
}

// PostWebhookV3WithBodyWithResponse request with arbitrary body returning *PostWebhookV3Response
func (c *ClientWithResponses) PostWebhookV3WithBodyWithResponse(ctx context.Context, params *PostWebhookV3Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWebhookV3Response, error) {
	rsp, err := c.PostWebhookV3WithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWebhookV3Response(rsp)
}

func (c *ClientWithResponses) PostWebhookV3WithResponse(ctx context.Context, params *PostWebhookV3Params, body PostWebhookV3JSONRequestBody, reqEditors ...RequestEditorFn) (*PostWebhookV3Response, error) {
	rsp, err := c.PostWebhookV3(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWebhookV3Response(rsp)
}

// ParsePostSendMessageResponse parses an HTTP response from a PostSendMessageWithResponse call
func ParsePostSendMessageResponse(rsp *http.Response) (*PostSendMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSendMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Content *struct {
				Text *string `json:"text,omitempty"`
			} `json:"content,omitempty"`
			Created   *int    `json:"created,omitempty"`
			Direction *string `json:"direction,omitempty"`
			Id        *string `json:"id,omitempty"`
			Type      *string `json:"type,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSendImageMessageResponse parses an HTTP response from a PostSendImageMessageWithResponse call
func ParsePostSendImageMessageResponse(rsp *http.Response) (*PostSendImageMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSendImageMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			AuthorId *int `json:"author_id,omitempty"`
			Content  *struct {
				Image *struct {
					Sizes *map[string]string `json:"sizes,omitempty"`
				} `json:"image,omitempty"`
			} `json:"content,omitempty"`
			Created   *int    `json:"created,omitempty"`
			Direction *string `json:"direction,omitempty"`
			Id        *string `json:"id,omitempty"`
			Type      *string `json:"type,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteMessageResponse parses an HTTP response from a DeleteMessageWithResponse call
func ParseDeleteMessageResponse(rsp *http.Response) (*DeleteMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseChatReadResponse parses an HTTP response from a ChatReadWithResponse call
func ParseChatReadResponse(rsp *http.Response) (*ChatReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChatReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok *bool `json:"ok,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetVoiceFilesResponse parses an HTTP response from a GetVoiceFilesWithResponse call
func ParseGetVoiceFilesResponse(rsp *http.Response) (*GetVoiceFilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVoiceFilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VoiceFiles
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUploadImagesResponse parses an HTTP response from a UploadImagesWithResponse call
func ParseUploadImagesResponse(rsp *http.Response) (*UploadImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]map[string]string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSubscriptionsResponse parses an HTTP response from a GetSubscriptionsWithResponse call
func ParseGetSubscriptionsResponse(rsp *http.Response) (*GetSubscriptionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSubscriptionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Subscriptions []struct {
				Url string `json:"url"`

				// Version Версия метода, через который вебхук добавлен. Влияет на формат получаемых данных
				Version string `json:"version"`
			} `json:"subscriptions"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostWebhookUnsubscribeResponse parses an HTTP response from a PostWebhookUnsubscribeWithResponse call
func ParsePostWebhookUnsubscribeResponse(rsp *http.Response) (*PostWebhookUnsubscribeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostWebhookUnsubscribeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok *bool `json:"ok,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostBlacklistV2Response parses an HTTP response from a PostBlacklistV2WithResponse call
func ParsePostBlacklistV2Response(rsp *http.Response) (*PostBlacklistV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostBlacklistV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetChatsV2Response parses an HTTP response from a GetChatsV2WithResponse call
func ParseGetChatsV2Response(rsp *http.Response) (*GetChatsV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChatsV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Chats
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetChatByIdV2Response parses an HTTP response from a GetChatByIdV2WithResponse call
func ParseGetChatByIdV2Response(rsp *http.Response) (*GetChatByIdV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChatByIdV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Chat
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMessagesV3Response parses an HTTP response from a GetMessagesV3WithResponse call
func ParseGetMessagesV3Response(rsp *http.Response) (*GetMessagesV3Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMessagesV3Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Messages
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostWebhookV3Response parses an HTTP response from a PostWebhookV3WithResponse call
func ParsePostWebhookV3Response(rsp *http.Response) (*PostWebhookV3Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostWebhookV3Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok *bool `json:"ok,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// Id Уникальный идентификатор сообщения webhooks
			Id      *string        `json:"id,omitempty"`
			Payload *PayloadStruct `json:"payload,omitempty"`

			// Timestamp Unix-timestamp времени отправки сообщения webhooks
			Timestamp *int `json:"timestamp,omitempty"`

			// Version Версия webhooks
			Version *string `json:"version,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}
