all: gen

.PHONY : gen

gen: codegen

swagger:
	@echo "Get swagger files ..."

codegen:
	@echo "Installing oapi-codegen ..."
	go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
	@echo "Generating api code for Autoload..."
	oapi-codegen -package=autoload -generate="types,client,spec" swagger/autoload.json > autoload/autoload.gen.go
	@echo "Generating api code for Announcements..."
	oapi-codegen -package=announcements -generate="types,client,spec" swagger/announcements.json > announcements/announcements.gen.go
	@echo "Generating api code for Authorization..."
	oapi-codegen -package=authorization -generate="types,client,spec" swagger/authorization.json > authorization/authorization.gen.go
	@echo "Generating api code for Messenger..."
	oapi-codegen -package=messenger -generate="types,client,spec" swagger/messenger.json > messenger/messenger.gen.go
	@echo "Generating api code for User info self..."
	oapi-codegen -package=userinfoself -generate="types,client,spec" swagger/userinfoself.json > userinfoself/userinfoself.gen.go
	@echo "Generating api code for Work..."
	oapi-codegen -package=work -generate="types,client,spec" --config=work/codegen.yaml swagger/work.json > work/work.gen.go
