// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package userinfoself

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	AuthorizationCodeScopes = "AuthorizationCode.Scopes"
	ClientCredentialsScopes = "ClientCredentials.Scopes"
)

// Defines values for ResponseOperationsHistoryItemOperationType.
const (
	Аванс                                                   ResponseOperationsHistoryItemOperationType = "аванс"
	ВнесениеCPAАванса                                       ResponseOperationsHistoryItemOperationType = "внесение CPA аванса"
	ВозвратCPAАванса                                        ResponseOperationsHistoryItemOperationType = "возврат CPA аванса"
	ВозвратАванса                                           ResponseOperationsHistoryItemOperationType = "возврат аванса"
	ВозвратЗарезервированныхСредствПодАвтостатегиюНаКошелек ResponseOperationsHistoryItemOperationType = "возврат зарезервированных средств под автостатегию на кошелек"
	ВозвратЗарзервированныхСредствНаБалансКошелька          ResponseOperationsHistoryItemOperationType = "возврат зарзервированных средств на баланс кошелька"
	Опротестовано                                           ResponseOperationsHistoryItemOperationType = "опротестовано"
	Постоплата                                              ResponseOperationsHistoryItemOperationType = "постоплата"
	ПризнаниеВыручки                                        ResponseOperationsHistoryItemOperationType = "признание выручки"
	РезервированиеПодАвтостратегию                          ResponseOperationsHistoryItemOperationType = "резервирование под автостратегию"
	РезервированиеСредствПодУслугу                          ResponseOperationsHistoryItemOperationType = "резервирование средств под услугу"
	СжиганиеБонусов                                         ResponseOperationsHistoryItemOperationType = "сжигание бонусов"
	СписаниеВСчётКредита                                    ResponseOperationsHistoryItemOperationType = "списание в счёт кредита"
	СписаниеОстатка                                         ResponseOperationsHistoryItemOperationType = "списание остатка"
	СписаниеСредствСКошелькаВДоходНеЗаОказанныеУслуги       ResponseOperationsHistoryItemOperationType = "списание средств с кошелька в доход (не за оказанные услуги)"
	Сторно                                                  ResponseOperationsHistoryItemOperationType = "сторно"
	Чарджбэк                                                ResponseOperationsHistoryItemOperationType = "чарджбэк"
)

// Valid indicates whether the value is a known member of the ResponseOperationsHistoryItemOperationType enum.
func (e ResponseOperationsHistoryItemOperationType) Valid() bool {
	switch e {
	case Аванс:
		return true
	case ВнесениеCPAАванса:
		return true
	case ВозвратCPAАванса:
		return true
	case ВозвратАванса:
		return true
	case ВозвратЗарезервированныхСредствПодАвтостатегиюНаКошелек:
		return true
	case ВозвратЗарзервированныхСредствНаБалансКошелька:
		return true
	case Опротестовано:
		return true
	case Постоплата:
		return true
	case ПризнаниеВыручки:
		return true
	case РезервированиеПодАвтостратегию:
		return true
	case РезервированиеСредствПодУслугу:
		return true
	case СжиганиеБонусов:
		return true
	case СписаниеВСчётКредита:
		return true
	case СписаниеОстатка:
		return true
	case СписаниеСредствСКошелькаВДоходНеЗаОказанныеУслуги:
		return true
	case Сторно:
		return true
	case Чарджбэк:
		return true
	default:
		return false
	}
}

// Defines values for ResponseOperationsHistoryItemServiceType.
const (
	Bundle       ResponseOperationsHistoryItemServiceType = "bundle"
	Cpa          ResponseOperationsHistoryItemServiceType = "cpa"
	Cv           ResponseOperationsHistoryItemServiceType = "cv"
	Lf           ResponseOperationsHistoryItemServiceType = "lf"
	PerfVas      ResponseOperationsHistoryItemServiceType = "perf_vas"
	Subscription ResponseOperationsHistoryItemServiceType = "subscription"
	Tariff       ResponseOperationsHistoryItemServiceType = "tariff"
	Vas          ResponseOperationsHistoryItemServiceType = "vas"
)

// Valid indicates whether the value is a known member of the ResponseOperationsHistoryItemServiceType enum.
func (e ResponseOperationsHistoryItemServiceType) Valid() bool {
	switch e {
	case Bundle:
		return true
	case Cpa:
		return true
	case Cv:
		return true
	case Lf:
		return true
	case PerfVas:
		return true
	case Subscription:
		return true
	case Tariff:
		return true
	case Vas:
		return true
	default:
		return false
	}
}

// Balance defines model for Balance.
type Balance struct {
	// Bonus Сумма бонусных средств
	Bonus *float32 `json:"bonus,omitempty"`

	// Real Сумма реальных денежных средств
	Real *float32 `json:"real,omitempty"`
}

// RequestOperationsHistory defines model for RequestOperationsHistory.
type RequestOperationsHistory struct {
	// DateTimeFrom Время выборки от. Не далее одного года в прошлое от текущего момента.
	DateTimeFrom time.Time `json:"dateTimeFrom"`

	// DateTimeTo Время выборки до (диапазон между dateTimeFrom и dateTimeTo должен быть не более одной недели)
	DateTimeTo time.Time `json:"dateTimeTo"`
}

// ResponseOperationsHistory defines model for ResponseOperationsHistory.
type ResponseOperationsHistory struct {
	Result *struct {
		Operations *[]ResponseOperationsHistoryItem `json:"operations,omitempty"`
	} `json:"result,omitempty"`
}

// ResponseOperationsHistoryItem defines model for ResponseOperationsHistoryItem.
type ResponseOperationsHistoryItem struct {
	// AmountBonus Сумма бонусов
	AmountBonus *float32 `json:"amountBonus,omitempty"`

	// AmountRub Сумма реальных денег
	AmountRub *float32 `json:"amountRub,omitempty"`

	// AmountTotal Сумма операции всего
	AmountTotal *float32 `json:"amountTotal,omitempty"`

	// ItemId ID объявления
	ItemId *int `json:"itemId,omitempty"`

	// OperationName Название операции
	OperationName *string `json:"operationName,omitempty"`

	// OperationType Тип операции
	OperationType *ResponseOperationsHistoryItemOperationType `json:"operationType,omitempty"`

	// PaidAt Дата/время оплаты операции
	PaidAt *string `json:"paidAt,omitempty"`

	// ServiceId Код типа услуги
	ServiceId *int `json:"serviceId,omitempty"`

	// ServiceName Название конкретного типа услуги
	ServiceName *string `json:"serviceName,omitempty"`

	// ServiceType Тип услуги
	ServiceType *ResponseOperationsHistoryItemServiceType `json:"serviceType,omitempty"`

	// UpdatedAt Дата/время совершения операции
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

// ResponseOperationsHistoryItemOperationType Тип операции
type ResponseOperationsHistoryItemOperationType string

// ResponseOperationsHistoryItemServiceType Тип услуги
type ResponseOperationsHistoryItemServiceType string

// UserInfoSelf defines model for UserInfoSelf.
type UserInfoSelf struct {
	// Email Email пользователя
	Email *string `json:"email,omitempty"`

	// Id Идентификатор пользователя
	Id *int32 `json:"id,omitempty"`

	// Name Имя пользователя
	Name *string `json:"name,omitempty"`

	// Phone первый верифицированный телефон пользователя
	Phone *string `json:"phone,omitempty"`

	// Phones все верифицированные номера телефонов
	Phones *[]string `json:"phones,omitempty"`

	// ProfileUrl Ссылка на профиль пользователя
	ProfileUrl *string `json:"profile_url,omitempty"`
}

// AuthError defines model for authError.
type AuthError struct {
	Error *struct {
		// Code Код ошибки
		Code int32 `json:"code"`

		// Message Сообщение об ошибке
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// ForbiddenError defines model for forbiddenError.
type ForbiddenError struct {
	Error *struct {
		// Code Код ошибки
		Code int32 `json:"code"`

		// Message Сообщение об ошибке
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// NotFoundError defines model for notFoundError.
type NotFoundError struct {
	Error *struct {
		// Code Код ошибки
		Code int32 `json:"code"`

		// Message Сообщение об ошибке
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// ServiceError defines model for serviceError.
type ServiceError struct {
	Error *struct {
		// Code Код ошибки
		Code int32 `json:"code"`

		// Message Описание ошибки
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// ServiceUnavailableError defines model for serviceUnavailableError.
type ServiceUnavailableError struct {
	Error *struct {
		// Code Код ошибки
		Code int32 `json:"code"`

		// Message Описание ошибки
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// AuthHeader defines model for authHeader.
type AuthHeader = string

// UserId defines model for userId.
type UserId = int64

// PostOperationsHistoryParams defines parameters for PostOperationsHistory.
type PostOperationsHistoryParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// GetUserInfoSelfParams defines parameters for GetUserInfoSelf.
type GetUserInfoSelfParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// GetUserBalanceParams defines parameters for GetUserBalance.
type GetUserBalanceParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`
}

// PostOperationsHistoryJSONRequestBody defines body for PostOperationsHistory for application/json ContentType.
type PostOperationsHistoryJSONRequestBody = RequestOperationsHistory

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostOperationsHistoryWithBody request with any body
	PostOperationsHistoryWithBody(ctx context.Context, params *PostOperationsHistoryParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOperationsHistory(ctx context.Context, params *PostOperationsHistoryParams, body PostOperationsHistoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserInfoSelf request
	GetUserInfoSelf(ctx context.Context, params *GetUserInfoSelfParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserBalance request
	GetUserBalance(ctx context.Context, userId UserId, params *GetUserBalanceParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostOperationsHistoryWithBody(ctx context.Context, params *PostOperationsHistoryParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOperationsHistoryRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOperationsHistory(ctx context.Context, params *PostOperationsHistoryParams, body PostOperationsHistoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOperationsHistoryRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserInfoSelf(ctx context.Context, params *GetUserInfoSelfParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserInfoSelfRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserBalance(ctx context.Context, userId UserId, params *GetUserBalanceParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserBalanceRequest(c.Server, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostOperationsHistoryRequest calls the generic PostOperationsHistory builder with application/json body
func NewPostOperationsHistoryRequest(server string, params *PostOperationsHistoryParams, body PostOperationsHistoryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOperationsHistoryRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostOperationsHistoryRequestWithBody generates requests for PostOperationsHistory with any type of body
func NewPostOperationsHistoryRequestWithBody(server string, params *PostOperationsHistoryParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v1/accounts/operations_history/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetUserInfoSelfRequest generates requests for GetUserInfoSelf
func NewGetUserInfoSelfRequest(server string, params *GetUserInfoSelfParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v1/accounts/self")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetUserBalanceRequest generates requests for GetUserBalance
func NewGetUserBalanceRequest(server string, userId UserId, params *GetUserBalanceParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v1/accounts/%s/balance/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostOperationsHistoryWithBodyWithResponse request with any body
	PostOperationsHistoryWithBodyWithResponse(ctx context.Context, params *PostOperationsHistoryParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOperationsHistoryResponse, error)

	PostOperationsHistoryWithResponse(ctx context.Context, params *PostOperationsHistoryParams, body PostOperationsHistoryJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOperationsHistoryResponse, error)

	// GetUserInfoSelfWithResponse request
	GetUserInfoSelfWithResponse(ctx context.Context, params *GetUserInfoSelfParams, reqEditors ...RequestEditorFn) (*GetUserInfoSelfResponse, error)

	// GetUserBalanceWithResponse request
	GetUserBalanceWithResponse(ctx context.Context, userId UserId, params *GetUserBalanceParams, reqEditors ...RequestEditorFn) (*GetUserBalanceResponse, error)
}

type PostOperationsHistoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ResponseOperationsHistory
	JSON401      *AuthError
	JSON500      *ServiceError
	JSON503      *ServiceUnavailableError
}

// Status returns HTTPResponse.Status
func (r PostOperationsHistoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOperationsHistoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserInfoSelfResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserInfoSelf
	JSON401      *AuthError
	JSON403      *ForbiddenError
	JSON500      *ServiceError
	JSON503      *ServiceUnavailableError
}

// Status returns HTTPResponse.Status
func (r GetUserInfoSelfResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserInfoSelfResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserBalanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Balance
	JSON401      *AuthError
	JSON403      *ForbiddenError
	JSON404      *NotFoundError
	JSON500      *ServiceError
	JSON503      *ServiceUnavailableError
}

// Status returns HTTPResponse.Status
func (r GetUserBalanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserBalanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostOperationsHistoryWithBodyWithResponse request with arbitrary body returning *PostOperationsHistoryResponse
func (c *ClientWithResponses) PostOperationsHistoryWithBodyWithResponse(ctx context.Context, params *PostOperationsHistoryParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOperationsHistoryResponse, error) {
	rsp, err := c.PostOperationsHistoryWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOperationsHistoryResponse(rsp)
}

func (c *ClientWithResponses) PostOperationsHistoryWithResponse(ctx context.Context, params *PostOperationsHistoryParams, body PostOperationsHistoryJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOperationsHistoryResponse, error) {
	rsp, err := c.PostOperationsHistory(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOperationsHistoryResponse(rsp)
}

// GetUserInfoSelfWithResponse request returning *GetUserInfoSelfResponse
func (c *ClientWithResponses) GetUserInfoSelfWithResponse(ctx context.Context, params *GetUserInfoSelfParams, reqEditors ...RequestEditorFn) (*GetUserInfoSelfResponse, error) {
	rsp, err := c.GetUserInfoSelf(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserInfoSelfResponse(rsp)
}

// GetUserBalanceWithResponse request returning *GetUserBalanceResponse
func (c *ClientWithResponses) GetUserBalanceWithResponse(ctx context.Context, userId UserId, params *GetUserBalanceParams, reqEditors ...RequestEditorFn) (*GetUserBalanceResponse, error) {
	rsp, err := c.GetUserBalance(ctx, userId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserBalanceResponse(rsp)
}

// ParsePostOperationsHistoryResponse parses an HTTP response from a PostOperationsHistoryWithResponse call
func ParsePostOperationsHistoryResponse(rsp *http.Response) (*PostOperationsHistoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOperationsHistoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResponseOperationsHistory
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest AuthError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ServiceUnavailableError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetUserInfoSelfResponse parses an HTTP response from a GetUserInfoSelfWithResponse call
func ParseGetUserInfoSelfResponse(rsp *http.Response) (*GetUserInfoSelfResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserInfoSelfResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserInfoSelf
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest AuthError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ServiceUnavailableError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetUserBalanceResponse parses an HTTP response from a GetUserBalanceWithResponse call
func ParseGetUserBalanceResponse(rsp *http.Response) (*GetUserBalanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserBalanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Balance
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest AuthError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ServiceUnavailableError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb/W4bV3Z/ldtJ/7C9JIcfkhUTKLCK1+kKLWIjdoACtiCMhlfSpOTM7MzQXjUQIFFx",
	"va7cqDUWRVBsms3uH/2jKEBRpETzS8A+wbmv0Ccpzrl3vsihTdmyFxsEMGRyZnjuOeeez9+585VmOg3X",
	"sbkd+Fr1K801PKPBA+7RN6MZ7PySGzXu4bca903PcgPLsbWqBn+ACQygB2MGXRiKYwZt6IgWTMQ+9OEc",
	"2uKfoQ99LadZ+PyOpJPTbKPBtaq22gx2HM/6J4Po5TSP/6ppebymVQOvyXOab+7whoHr8l8bDbeOv/mE",
	"Gx732Ort23fu3994cPfv7nym5bRg18WbfuBZ9ra2t5fTmj731moZPH8LXeRYtKAvvoY+DKAtOWZwARMY",
	"ihdwDhPo0OUeSXUNBjCEvvpZ+3ooj2sEO7E0uOKGVXutHFuO1zACrapZdnBzKWbcsgO+zT1tD1mXj5P2",
	"PzHqhm1y2hbPcbkXWJxubDp208+Q7gdxCCMYQZvBCUxgLA7FAYzFkXjKxIHYhx50xYFoQUfLxcxs1R0j",
	"iJmxm41N5AUFMeqvXYQotklpchGpXOjB2duuuhddcTa/5GaAfHzOf9XkfnDX5R7Ziv9Lyw8cb3dWLzUj",
	"4A+sBv/UcxoZnL8kZkZoqR1xhCoS+zCAPoOJaBUYfAc9FKENQ+jhxwl0YQwTOIUJwz94j0GHwYXYh4n4",
	"DQxhQs+JFiNzGYhD8Rx68gcjmMAotJpCUnZkMx9YDT5ru7lIhgfOpSTowoRdgy70oQ0X0CYrHjNi4Ay6",
	"4pAldcOgz+J16McwhDPpyyfiSLTEC4YbKe1oSh2v6Bbt9RD61xeUbC/pGQ/TW5WSej3TBHzXsX2+gA14",
	"3G/Wg9nrTvRT/GYFvEEf/trjW1pV+0iPw6CuXFCfu+pawBtabKqG5xm7Wba7dxlRiOgM20bDadrBJ5dx",
	"+Al52ow7S0qfNzff0qdP5xN94ARvCBUwgQvoif0wKaD9HkhPySKL25MVv9d+gZROxL+IY+iQXY6hL44z",
	"Qmku3vDPKELPMPcdeUkH2khD2neKxSznjGg+oDsZKbEPF1mUuN1soNmLA7iAvjiIV+1gkHwm/l20GAxk",
	"tIQ+hgwtp2FOotCJBIeUk+hyBzeE9CeJ3L63SskXqSJt+cwExSMuWplPRF9nH596dIbrdFxn4oDBgCJi",
	"jyxnoOJkFybiKcYNdk1Gk3NpCgNSPRIbiyMkh2Y7FIdwKuOJOIAz6MNprKVp66blz0nJHehjOE7u5AWt",
	"GZUjB6Il5SKD64tvMgTGcmUezaxclrVIcgmMke2EVjA7vInv7BVi5YjDuYwvzvZYBgtMcrTBMztHdqdK",
	"uHHCTsWR2BeH4hnmmyybSOhgoKxGFYNjcnI0YsqbLbRdMmrJJ94Uz0iMLpzBifhXGCSyQOx9rmHVVoMM",
	"t/utdA2dtKLyY+Qy4mgh1/a599gyeWbV+J9yI1ro3RgjE+aaGXoUrUUDzwCNWzq/aEUVxxuWm+H8tSFp",
	"ikYYjh4bvpbTXO5tbciP9S0tp5mPcRnDs7bwm9/cjAnmNNM1tJy22bRrdZ65S00Xk/nCGyVdGneHjJDi",
	"+QIblpVav8Cq395y7vP61mwm5Q3DykhSd/Dy3OofdRV1H+rTz2tOw7DsgkmVy4z81tX0HcmVby2VK8uV",
	"UimXaiEq5Uzjs7Ot7lvpFovICd+jIYr9LOncHcfOIi+3C4vSV0xup5QU9y8dk+CVLJaH0BNfyyp1AaZW",
	"SqVSuVyuVJaW5nGVVSBRlfEmhnqMnG4kLW6KO5VwooIxVlOCpSxNpYvDHFrjllXnG00vu1Q6EEcwlKmT",
	"YrQMlmgsQ6zGF9m4nSBw/aquG4+twCl4TR27Un2lVlwya2bFKJVXyjc55ytl8+bHyyXz1nLFMJeXdMXZ",
	"Yk5mNIOdO57neBkeln3ZdGp8blCl3NOHE5VVIlmWiotZe4P7vrGdRf8HmFCt+Dwqk/BrcsFeSnlf2IZC",
	"JHjtje0LyRSvvr5Q6b/leJtWrcbtD6K/ygfW36ehdO9HebYTfOo07doH0d3SB9bdZ07AtlC696M7VSF8",
	"ANUtF4vvqLr/mi0rM1fSSBr2ZMeqc+Z6jsl937K3mSfRogK7V+eGz3PMdOzAMAPmN13X8YL3quEvbOOx",
	"YdWNzfqHUXblQyn7vpSPBbzhOp7hWfVd1oyF/aDaJnWbTc8Kdu+bO7whNZiCk29nq/N/seZiq/fWGEkd",
	"pVRxiAUPu4s0WJnaWSwGniq9nEssjxnJJTaQ8wKDb6cIvcLMzEIQUAHjXdWFHlJBDwMJM8rqY8Sgi50V",
	"9Y1P5yR66GFdRW0ZwyIFzunvCbVTA9k7ymYLS5ZxuLzs44YwkeAe1tYF9hC+R7OiZ0/o2d76Nd1wrbxp",
	"BEbd2dZRUL3mmM0GtwOS9qPA2NZXXbdumfR91UR/I+yv7jyJZgUzG5C6+AVWPrNFioMPYaNhOi4PSTl1",
	"x6hVPY5G5MuaFNWC/WccUkULv8pWksG/yU6ckIVT0ui5smMq3qqG69Z3qc9BcqSZkcK2FMEu9R0TGJKq",
	"WqonVn101EFFBC17y5nDWh/GWD6KfRjFkJdMAbPwlXiq5bQvnU3iUCnYvzxhsoShai6eqioSq9yBgnJk",
	"I4ULmY8vQV5iFuIb1Jb6/RPPCrjsKs6nlTgjYNQRUEc7IOihz+D3kf22VQDg9jb3qh43akj6v2kDQmRk",
	"KqG+InxpREiCxMG6aOLIKhkCbd8kRTfi+XeEZGc1A++2lL/jeMFGwL3GhsftIBLk3c1DIoMSWZkQoDMR",
	"z0IsXuJWY+iKowwmLr1Ti68UGIH/GiEjNKhPn/pq0jK7pibndZfX19xYqShubMoB2usoJ5AwarrmdllE",
	"MB4ivJbbKBirfU1iGa/mL4KpzvlHPh0nXasQxUq6n0qKGDzL+NPbdYvbwW2P17gdWEbdv/oEaNISG2a8",
	"xtsnQAljjig1jdXdYxih/+EtyndD6EfWJ1Ws8LFXhHuq4qU/J6XJnDWbqMwsRUXJ5102AS/JpIAVHRVC",
	"CeRJUzVRmN1+HhKksV9qo2iHlOou0gaGl6aMdgZ6n2NguTebZj/pa+nIlB7uR/gJGcY8R3xk37gRx0iW",
	"FOtEAcw95Xhq9KFAZIwP4phgqIMQJDwlPPcAl2QP4Y+Yjmm1PtlN2qDjkC6O16+Fu/jkyZN4F+t826jr",
	"rudsBI5T93W3uVm3zLzhWtcLN24wxtgjamWtoK4C6FQMIpzydTHoMfd8uZ8lNTyyDdfSqlqlUCwUtRwd",
	"ISDr003H4/rjkm6YptO0A1+PI83GjpwP6tPHMx5mTy/jR/TE8Y299ZzmOn4WKPsyMVB4Dm2KBBG6P0Ff",
	"XTSCsWvpqYA41unRsKbqJRDvlMXm1ZhRvMAqmMwwmviIo+vR4Ci0kp7KHmOFN0o0WV6S4UEy3FfDJwwW",
	"XSka2dPcInt0nTY90v4axvh7TtbpA9nHcD/4xKnthh7PbdJwopDTv/RRzQngcPqcglYulov54lK+WHpQ",
	"LFbpX3oknnjk4/iRveTZktfPseccoNjbk+2YnEiTJZaLxcvJkpyrP5yaVxdTU+dS6dbUwJiuhLPe0sfL",
	"lfLyyq1bN2dmtxr8fuGxWYHJ0EANVZv96X/gB2UwbTrW8A9/n1WE9GD0p2EUmzKKMPZ/X/9HzKE2Mwq+",
	"gsleYgJVujk1RNIWlUKbmgepEU9iKBPZUnnlQalYXS5Vl4uFYqm8VLn5s2KFDGv9EqY172AGmdZUpPkj",
	"hYee+E3ouFj9Y2vQQmNeKpYWML3F+IpR6iw+/kC7cSKrHhkQ2uJQ9hupEQ1FeeRteSG3WIy3FBqXxd5L",
	"CnwtVW2PxTHZZITMtGVx1lIHklbvrUkOK1fN4QyalcXs70JWZHafCsXhUaG4+uvBOAXhUNTIAG8eZlfc",
	"63u5r7JK3YfrmOH8ZqNheLtXXJfntMDYxjVowqitI/uzGdtXU8dtvmiShf7lTyMi47K0JkWfSqEiKSbx",
	"SCtGmHoZOe1veZAal75VGljMmlLr/LjCwtIVOt3UdCiLwe+gp0aZUlEPsBHR76JU7D42MD+Fqj9fqLqC",
	"+DQXFXqb3ms2bOXepX3IjHlfqWPPe7qCWvTLRUBxIE8IisNLHyYmVC7dR/RyTI7v2zCAM1l2heTfcCB6",
	"foQMD2G/xwAZLvFTbHzfsXGpuHRlPKUH0ouwpJyFLJfgK4JXD6D3U9j+M1aYKZD4XcL3W6JyVxunc298",
	"Wr0bs7e+p+bW4SrN+YgnwUeKy+nA/hH78aCVMwNxEo38lOh0FPpEdtdhiWzdgh57eOPG/SfG9jb3WKVQ",
	"vHEjBh63rWCnuVkwnYZ+d3VNv+tye/XeWv6+y01rK/SgzbqzqTcMP+CerqBDXyeosNCoXS88suGlOGIK",
	"Mu9JlD0D9JQvb3STx+2+hja8giS+IY/2DujUW4xxhLi/cnwYQR81MJ1WQzKnMkEndX+iXj3phK/NDMLX",
	"ZuRv4qm1OMLlSL9jOuRK09eTcIvUEijPARPHcC6OaM6tNuOUCI2QwyTUomS4ILkm4rl4Ib5hlKb6NEzA",
	"VRO7hHFgm9vJnfLlrYLlhB/zpnxKv84kFebYdcvmDCO3QnvQsBN079SswPGSZDldKSSo44b+5cLjj2yM",
	"gOFbHCM5zgnzWRtG8za6R6jVUzmBxT2SMJaqCdF0ZW3RYfADQWNnWHMwOd5B1xP7cCYnieH5SDmXla1v",
	"qn7E0EC9MRWBsk6ZQKf6yH7ULBYrZt2i/3n6vGeVybub8ubPVtjSrWW2srKSLxXzN2/Km7q6q76FlKYp",
	"0+AnJGiwHY9v/c0jDS8GTnXeNOiRJn88975c05jHgf0Rk4e+MVhkvpGJD8FvFZwwzyyiEKI8mTYwUbXM",
	"e2ssM/AWGLxMx6Tk63GSduwHmbNJsmes1w/FN+K5zLhTM8q5ApOrSU39VT7PPue/cMz8mv0lN4Nwd8Ji",
	"IV/jW5ZtEeIkVcry+Vi3s3NGJqNcG85IIaPZyWkvAdqQjVLwjSqHPounoKFVP5OvAEmNdtSZhLDwlx2L",
	"0kMv9LXzcCxSoF5GvZZKFUVO+3W+Zvlu3dgN0eTvM3PuC6wK/j8AAP//qTpt1RI8AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
