// Package cpa provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package cpa

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ClientCredentialsScopes = "ClientCredentials.Scopes"
)

// Defines values for CallV2StatusId.
const (
	N0 CallV2StatusId = 0
	N1 CallV2StatusId = 1
	N2 CallV2StatusId = 2
	N3 CallV2StatusId = 3
)

// Valid indicates whether the value is a known member of the CallV2StatusId enum.
func (e CallV2StatusId) Valid() bool {
	switch e {
	case N0:
		return true
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	default:
		return false
	}
}

// CallById defines model for CallById.
type CallById struct {
	// CallId Идентификатор звонка
	CallId int64 `json:"callId"`
}

// CallV2 defines model for CallV2.
type CallV2 struct {
	// BuyerPhone Телефонный номер покупателя
	BuyerPhone *string `json:"buyerPhone,omitempty"`

	// CreateTime Время поступления звонка (строка в формате RFC3339)
	CreateTime *string `json:"createTime,omitempty"`

	// Duration Время разговора в секундах
	Duration *int `json:"duration,omitempty"`

	// GroupTitle Название группы
	GroupTitle *string `json:"groupTitle,omitempty"`

	// Id Идентификатор звонка
	Id *int64 `json:"id,omitempty"`

	// IsArbitrageAvailable Флаг, указывающий на то, доступен ли арбитраж по звонку
	IsArbitrageAvailable *bool `json:"isArbitrageAvailable,omitempty"`

	// ItemId Идентификатор объявления
	ItemId *int64 `json:"itemId,omitempty"`

	// Price Цена звонка CPA в копейках
	Price *int64 `json:"price,omitempty"`

	// RecordUrl Ссылка на запись звонка
	RecordUrl *string `json:"recordUrl,omitempty"`

	// SellerPhone Реальный телефонный номер продавца
	SellerPhone *string `json:"sellerPhone,omitempty"`

	// StartTime Время начала разговора (строка в формате RFC3339)
	StartTime *string `json:"startTime,omitempty"`

	// StatusId Статус звонка (0 - целевой, 1 - на модерации, 2 - помечен как целевой после модерации,
	// 3 - помечен как нецелевой после модерации)
	StatusId *CallV2StatusId `json:"statusId,omitempty"`

	// VirtualPhone Виртуальный телефонный номер продавца
	VirtualPhone *string `json:"virtualPhone,omitempty"`

	// WaitingDuration Время ожидания в секундах
	WaitingDuration *float32 `json:"waitingDuration,omitempty"`
}

// CallV2StatusId Статус звонка (0 - целевой, 1 - на модерации, 2 - помечен как целевой после модерации,
// 3 - помечен как нецелевой после модерации)
type CallV2StatusId int64

// CallsByTime defines model for CallsByTime.
type CallsByTime struct {
	// DateTimeFrom Время с которого нужно начинать поиск звонков по startTime (строка в формате RFC3339)
	DateTimeFrom string `json:"dateTimeFrom"`

	// Limit Размер выборки
	Limit int64 `json:"limit"`

	// Offset Смещение выборки (по-умолчанию 0). Для улучшения производительности лучше использовать
	// максимальный startTime звонка из предыдущей выборки
	Offset *int64 `json:"offset,omitempty"`
}

// CpaError defines model for CpaError.
type CpaError struct {
	// Code Внутренний код ошибки
	//
	// Возможные значения:
	// - 1000 - пустой запрос
	// - 1001 - ошибка валидации
	// - 1002 - ошибка авторизации
	// - 1003 - внутренняя ошибка
	// - 1004 - не найдено
	Code *int64 `json:"code,omitempty"`

	// Message Текст ошибки
	Message *string `json:"message,omitempty"`
}

// CpaErrorChat defines model for CpaErrorChat.
type CpaErrorChat struct {
	Result *struct {
		// Message Текст ошибки
		Message *string `json:"message,omitempty"`
		Status  *bool   `json:"status,omitempty"`
	} `json:"result,omitempty"`
}

// CreateComplaint defines model for CreateComplaint.
type CreateComplaint struct {
	// CallId Идентификатор звонка
	CallId int64 `json:"callId"`

	// Message Текст жалобы
	Message string `json:"message"`
}

// CreateComplaintV4In defines model for CreateComplaintV4In.
type CreateComplaintV4In struct {
	// ActionId ID действия (action), по которому подаётся жалоба
	ActionId int `json:"actionId"`

	// Message Сообщение, прикрепленное к жалобе
	Message string `json:"message"`
}

// InternalError defines model for InternalError.
type InternalError struct {
	Result struct {
		Error struct {
			Code    int    `json:"code"`
			Message string `json:"message"`
		} `json:"error"`
	} `json:"result"`
}

// OpenAPIChatsByTimeIn defines model for OpenAPIChatsByTimeIn.
type OpenAPIChatsByTimeIn struct {
	// DateTimeFrom Время с которого нужно начинать поиск чатов по date (строка в формате RFC3339)
	DateTimeFrom string `json:"dateTimeFrom"`

	// Limit Размер выборки (значение в поле должно быть не более 100)
	Limit int `json:"limit"`

	// Offset Смещение выборки (по-умолчанию 0). Для улучшения производительности лучше использовать максимальный startTime чата из предыдущей выборки
	Offset int `json:"offset"`
}

// OpenAPIPhonesInfoFromChatsIn defines model for OpenAPIPhonesInfoFromChatsIn.
type OpenAPIPhonesInfoFromChatsIn struct {
	// DateTimeFrom Время с которого начинается поиск
	DateTimeFrom string `json:"dateTimeFrom"`
	Limit        int    `json:"limit"`
	Offset       int    `json:"offset"`
}

// OpenAPIPhonesInfoFromChatsOut defines model for OpenAPIPhonesInfoFromChatsOut.
type OpenAPIPhonesInfoFromChatsOut struct {
	// Date Время отправки сообщения
	Date string `json:"date"`

	// Group Прайсинговая группа объявления
	Group string `json:"group"`

	// Id ID ЦД
	Id int `json:"id"`

	// PhoneNumber Номер телефона из сообщения
	PhoneNumber *string `json:"phone_number,omitempty"`

	// PricePenny Цена ЦД в копейках
	PricePenny int `json:"pricePenny"`

	// Url URL до картинки с превью
	Url string `json:"url"`
}

// OpenApiChat defines model for OpenApiChat.
type OpenApiChat struct {
	// ActionId ID ЦД
	ActionId int `json:"actionId"`

	// ChannelId ID канала чата
	ChannelId string `json:"channelId"`

	// ContactType Тип контакта (email/phone/nick/other)
	ContactType string `json:"contactType"`

	// Date Время отправки сообщения
	Date string `json:"date"`

	// Group Прайсинговая группа объявления
	Group string `json:"group"`

	// Message Текст сообщения
	Message string `json:"message"`

	// MessageId ID сообщения
	MessageId string `json:"messageId"`

	// PricePenny Цена ЦД в копейках
	PricePenny int `json:"pricePenny"`

	// Status Статус ЦД
	Status string `json:"status"`

	// TargetChatType Тип целевого чата (Контакты/Cделка/Переключения)
	TargetChatType string `json:"targetChatType"`
}

// OpenApiChatsBuyer defines model for OpenApiChatsBuyer.
type OpenApiChatsBuyer struct {
	// BuyerId ID баера
	BuyerId int `json:"buyerId"`

	// Name Имя баера
	Name string `json:"name"`

	// Url URL до картинки с превью
	Url string `json:"url"`
}

// OpenApiChatsComposition defines model for OpenApiChatsComposition.
type OpenApiChatsComposition struct {
	Buyer OpenApiChatsBuyer `json:"buyer"`
	Chat  OpenApiChat       `json:"chat"`

	// IsArbitrageAvailable Доступность опротестования ЦД
	IsArbitrageAvailable bool             `json:"isArbitrageAvailable"`
	Item                 OpenApiChatsItem `json:"item"`
}

// OpenApiChatsItem defines model for OpenApiChatsItem.
type OpenApiChatsItem struct {
	// ItemId ID объявления
	ItemId int `json:"itemId"`

	// PricePenny Цена объявления в копейках
	PricePenny int `json:"pricePenny"`

	// Title Название объявления
	Title string `json:"title"`

	// Url URL до картинки с превью
	Url string `json:"url"`
}

// OpenApiError defines model for OpenApiError.
type OpenApiError struct {
	Result struct {
		Error struct {
			Code    int    `json:"code"`
			Message string `json:"message"`
			Payload *struct {
				Error *string `json:"error,omitempty"`
			} `json:"payload,omitempty"`
		} `json:"error"`
	} `json:"result"`
}

// NotFoundError defines model for notFoundError.
type NotFoundError struct {
	Error *struct {
		// Code Код ошибки
		Code int32 `json:"code"`

		// Message Сообщение об ошибке
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// ServiceError defines model for serviceError.
type ServiceError struct {
	Error *struct {
		// Code Код ошибки
		Code int32 `json:"code"`

		// Message Описание ошибки
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// TooManyRequestsError defines model for tooManyRequestsError.
type TooManyRequestsError struct {
	Error *struct {
		// Code Код ошибки
		Code int32 `json:"code"`
	} `json:"error,omitempty"`
}

// AuthHeader defines model for authHeader.
type AuthHeader = string

// SourceHeader defines model for sourceHeader.
type SourceHeader = string

// N400 defines model for 400.
type N400 = OpenApiError

// N401 defines model for 401.
type N401 = CpaError

// N403 defines model for 403.
type N403 = CpaErrorChat

// N404 defines model for 404.
type N404 = CpaError

// N500 defines model for 500.
type N500 = InternalError

// GetCallParams defines parameters for GetCall.
type GetCallParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// ChatByActionIdParams defines parameters for ChatByActionId.
type ChatByActionIdParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// PostCreateComplaintParams defines parameters for PostCreateComplaint.
type PostCreateComplaintParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// CreateComplaintByActionIdParams defines parameters for CreateComplaintByActionId.
type CreateComplaintByActionIdParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// PhonesInfoFromChatsParams defines parameters for PhonesInfoFromChats.
type PhonesInfoFromChatsParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// BalanceInfoV2JSONBody defines parameters for BalanceInfoV2.
type BalanceInfoV2JSONBody = string

// BalanceInfoV2Params defines parameters for BalanceInfoV2.
type BalanceInfoV2Params struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// GetCallByIdV2Params defines parameters for GetCallByIdV2.
type GetCallByIdV2Params struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// GetCallsByTimeV2Params defines parameters for GetCallsByTimeV2.
type GetCallsByTimeV2Params struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// ChatsByTimeParams defines parameters for ChatsByTime.
type ChatsByTimeParams struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// BalanceInfoV3JSONBody defines parameters for BalanceInfoV3.
type BalanceInfoV3JSONBody = string

// BalanceInfoV3Params defines parameters for BalanceInfoV3.
type BalanceInfoV3Params struct {
	// Authorization Токен для авторизации
	Authorization AuthHeader `json:"Authorization"`

	// XSource Имя сервиса, отправляющего запрос
	XSource SourceHeader `json:"X-Source"`
}

// ChatsByTimeJSONRequestBody defines body for ChatsByTime for application/json ContentType.
type ChatsByTimeJSONRequestBody = OpenAPIChatsByTimeIn

// PostCreateComplaintJSONRequestBody defines body for PostCreateComplaint for application/json ContentType.
type PostCreateComplaintJSONRequestBody = CreateComplaint

// CreateComplaintByActionIdJSONRequestBody defines body for CreateComplaintByActionId for application/json ContentType.
type CreateComplaintByActionIdJSONRequestBody = CreateComplaintV4In

// PhonesInfoFromChatsJSONRequestBody defines body for PhonesInfoFromChats for application/json ContentType.
type PhonesInfoFromChatsJSONRequestBody = OpenAPIPhonesInfoFromChatsIn

// BalanceInfoV2JSONRequestBody defines body for BalanceInfoV2 for application/json ContentType.
type BalanceInfoV2JSONRequestBody = BalanceInfoV2JSONBody

// GetCallByIdV2JSONRequestBody defines body for GetCallByIdV2 for application/json ContentType.
type GetCallByIdV2JSONRequestBody = CallById

// GetCallsByTimeV2JSONRequestBody defines body for GetCallsByTimeV2 for application/json ContentType.
type GetCallsByTimeV2JSONRequestBody = CallsByTime

// BalanceInfoV3JSONRequestBody defines body for BalanceInfoV3 for application/json ContentType.
type BalanceInfoV3JSONRequestBody = BalanceInfoV3JSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCall request
	GetCall(ctx context.Context, callId int64, params *GetCallParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ChatByActionId request
	ChatByActionId(ctx context.Context, actionId int, params *ChatByActionIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ChatsByTimeWithBody request with any body
	ChatsByTimeWithBody(ctx context.Context, params *ChatsByTimeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChatsByTime(ctx context.Context, params *ChatsByTimeParams, body ChatsByTimeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCreateComplaintWithBody request with any body
	PostCreateComplaintWithBody(ctx context.Context, params *PostCreateComplaintParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCreateComplaint(ctx context.Context, params *PostCreateComplaintParams, body PostCreateComplaintJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateComplaintByActionIdWithBody request with any body
	CreateComplaintByActionIdWithBody(ctx context.Context, params *CreateComplaintByActionIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateComplaintByActionId(ctx context.Context, params *CreateComplaintByActionIdParams, body CreateComplaintByActionIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PhonesInfoFromChatsWithBody request with any body
	PhonesInfoFromChatsWithBody(ctx context.Context, params *PhonesInfoFromChatsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PhonesInfoFromChats(ctx context.Context, params *PhonesInfoFromChatsParams, body PhonesInfoFromChatsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BalanceInfoV2WithBody request with any body
	BalanceInfoV2WithBody(ctx context.Context, params *BalanceInfoV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BalanceInfoV2(ctx context.Context, params *BalanceInfoV2Params, body BalanceInfoV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCallByIdV2WithBody request with any body
	GetCallByIdV2WithBody(ctx context.Context, params *GetCallByIdV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetCallByIdV2(ctx context.Context, params *GetCallByIdV2Params, body GetCallByIdV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCallsByTimeV2WithBody request with any body
	GetCallsByTimeV2WithBody(ctx context.Context, params *GetCallsByTimeV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetCallsByTimeV2(ctx context.Context, params *GetCallsByTimeV2Params, body GetCallsByTimeV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BalanceInfoV3WithBody request with any body
	BalanceInfoV3WithBody(ctx context.Context, params *BalanceInfoV3Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BalanceInfoV3(ctx context.Context, params *BalanceInfoV3Params, body BalanceInfoV3JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCall(ctx context.Context, callId int64, params *GetCallParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCallRequest(c.Server, callId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChatByActionId(ctx context.Context, actionId int, params *ChatByActionIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChatByActionIdRequest(c.Server, actionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChatsByTimeWithBody(ctx context.Context, params *ChatsByTimeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChatsByTimeRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChatsByTime(ctx context.Context, params *ChatsByTimeParams, body ChatsByTimeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChatsByTimeRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCreateComplaintWithBody(ctx context.Context, params *PostCreateComplaintParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateComplaintRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCreateComplaint(ctx context.Context, params *PostCreateComplaintParams, body PostCreateComplaintJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateComplaintRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateComplaintByActionIdWithBody(ctx context.Context, params *CreateComplaintByActionIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateComplaintByActionIdRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateComplaintByActionId(ctx context.Context, params *CreateComplaintByActionIdParams, body CreateComplaintByActionIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateComplaintByActionIdRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PhonesInfoFromChatsWithBody(ctx context.Context, params *PhonesInfoFromChatsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPhonesInfoFromChatsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PhonesInfoFromChats(ctx context.Context, params *PhonesInfoFromChatsParams, body PhonesInfoFromChatsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPhonesInfoFromChatsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BalanceInfoV2WithBody(ctx context.Context, params *BalanceInfoV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBalanceInfoV2RequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BalanceInfoV2(ctx context.Context, params *BalanceInfoV2Params, body BalanceInfoV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBalanceInfoV2Request(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCallByIdV2WithBody(ctx context.Context, params *GetCallByIdV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCallByIdV2RequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCallByIdV2(ctx context.Context, params *GetCallByIdV2Params, body GetCallByIdV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCallByIdV2Request(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCallsByTimeV2WithBody(ctx context.Context, params *GetCallsByTimeV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCallsByTimeV2RequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCallsByTimeV2(ctx context.Context, params *GetCallsByTimeV2Params, body GetCallsByTimeV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCallsByTimeV2Request(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BalanceInfoV3WithBody(ctx context.Context, params *BalanceInfoV3Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBalanceInfoV3RequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BalanceInfoV3(ctx context.Context, params *BalanceInfoV3Params, body BalanceInfoV3JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBalanceInfoV3Request(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCallRequest generates requests for GetCall
func NewGetCallRequest(server string, callId int64, params *GetCallParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "call_id", callId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v1/call/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewChatByActionIdRequest generates requests for ChatByActionId
func NewChatByActionIdRequest(server string, actionId int, params *ChatByActionIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "actionId", actionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v1/chatByActionId/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewChatsByTimeRequest calls the generic ChatsByTime builder with application/json body
func NewChatsByTimeRequest(server string, params *ChatsByTimeParams, body ChatsByTimeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChatsByTimeRequestWithBody(server, params, "application/json", bodyReader)
}

// NewChatsByTimeRequestWithBody generates requests for ChatsByTime with any type of body
func NewChatsByTimeRequestWithBody(server string, params *ChatsByTimeParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v1/chatsByTime")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewPostCreateComplaintRequest calls the generic PostCreateComplaint builder with application/json body
func NewPostCreateComplaintRequest(server string, params *PostCreateComplaintParams, body PostCreateComplaintJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCreateComplaintRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostCreateComplaintRequestWithBody generates requests for PostCreateComplaint with any type of body
func NewPostCreateComplaintRequestWithBody(server string, params *PostCreateComplaintParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v1/createComplaint")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewCreateComplaintByActionIdRequest calls the generic CreateComplaintByActionId builder with application/json body
func NewCreateComplaintByActionIdRequest(server string, params *CreateComplaintByActionIdParams, body CreateComplaintByActionIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateComplaintByActionIdRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateComplaintByActionIdRequestWithBody generates requests for CreateComplaintByActionId with any type of body
func NewCreateComplaintByActionIdRequestWithBody(server string, params *CreateComplaintByActionIdParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v1/createComplaintByActionId")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewPhonesInfoFromChatsRequest calls the generic PhonesInfoFromChats builder with application/json body
func NewPhonesInfoFromChatsRequest(server string, params *PhonesInfoFromChatsParams, body PhonesInfoFromChatsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPhonesInfoFromChatsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPhonesInfoFromChatsRequestWithBody generates requests for PhonesInfoFromChats with any type of body
func NewPhonesInfoFromChatsRequestWithBody(server string, params *PhonesInfoFromChatsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v1/phonesInfoFromChats")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewBalanceInfoV2Request calls the generic BalanceInfoV2 builder with application/json body
func NewBalanceInfoV2Request(server string, params *BalanceInfoV2Params, body BalanceInfoV2JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBalanceInfoV2RequestWithBody(server, params, "application/json", bodyReader)
}

// NewBalanceInfoV2RequestWithBody generates requests for BalanceInfoV2 with any type of body
func NewBalanceInfoV2RequestWithBody(server string, params *BalanceInfoV2Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v2/balanceInfo")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewGetCallByIdV2Request calls the generic GetCallByIdV2 builder with application/json body
func NewGetCallByIdV2Request(server string, params *GetCallByIdV2Params, body GetCallByIdV2JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetCallByIdV2RequestWithBody(server, params, "application/json", bodyReader)
}

// NewGetCallByIdV2RequestWithBody generates requests for GetCallByIdV2 with any type of body
func NewGetCallByIdV2RequestWithBody(server string, params *GetCallByIdV2Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v2/callById")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewGetCallsByTimeV2Request calls the generic GetCallsByTimeV2 builder with application/json body
func NewGetCallsByTimeV2Request(server string, params *GetCallsByTimeV2Params, body GetCallsByTimeV2JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetCallsByTimeV2RequestWithBody(server, params, "application/json", bodyReader)
}

// NewGetCallsByTimeV2RequestWithBody generates requests for GetCallsByTimeV2 with any type of body
func NewGetCallsByTimeV2RequestWithBody(server string, params *GetCallsByTimeV2Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v2/callsByTime")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

// NewBalanceInfoV3Request calls the generic BalanceInfoV3 builder with application/json body
func NewBalanceInfoV3Request(server string, params *BalanceInfoV3Params, body BalanceInfoV3JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBalanceInfoV3RequestWithBody(server, params, "application/json", bodyReader)
}

// NewBalanceInfoV3RequestWithBody generates requests for BalanceInfoV3 with any type of body
func NewBalanceInfoV3RequestWithBody(server string, params *BalanceInfoV3Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cpa/v3/balanceInfo")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Source", params.XSource, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Source", headerParam1)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCallWithResponse request
	GetCallWithResponse(ctx context.Context, callId int64, params *GetCallParams, reqEditors ...RequestEditorFn) (*GetCallResponse, error)

	// ChatByActionIdWithResponse request
	ChatByActionIdWithResponse(ctx context.Context, actionId int, params *ChatByActionIdParams, reqEditors ...RequestEditorFn) (*ChatByActionIdResponse, error)

	// ChatsByTimeWithBodyWithResponse request with any body
	ChatsByTimeWithBodyWithResponse(ctx context.Context, params *ChatsByTimeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChatsByTimeResponse, error)

	ChatsByTimeWithResponse(ctx context.Context, params *ChatsByTimeParams, body ChatsByTimeJSONRequestBody, reqEditors ...RequestEditorFn) (*ChatsByTimeResponse, error)

	// PostCreateComplaintWithBodyWithResponse request with any body
	PostCreateComplaintWithBodyWithResponse(ctx context.Context, params *PostCreateComplaintParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateComplaintResponse, error)

	PostCreateComplaintWithResponse(ctx context.Context, params *PostCreateComplaintParams, body PostCreateComplaintJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateComplaintResponse, error)

	// CreateComplaintByActionIdWithBodyWithResponse request with any body
	CreateComplaintByActionIdWithBodyWithResponse(ctx context.Context, params *CreateComplaintByActionIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateComplaintByActionIdResponse, error)

	CreateComplaintByActionIdWithResponse(ctx context.Context, params *CreateComplaintByActionIdParams, body CreateComplaintByActionIdJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateComplaintByActionIdResponse, error)

	// PhonesInfoFromChatsWithBodyWithResponse request with any body
	PhonesInfoFromChatsWithBodyWithResponse(ctx context.Context, params *PhonesInfoFromChatsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PhonesInfoFromChatsResponse, error)

	PhonesInfoFromChatsWithResponse(ctx context.Context, params *PhonesInfoFromChatsParams, body PhonesInfoFromChatsJSONRequestBody, reqEditors ...RequestEditorFn) (*PhonesInfoFromChatsResponse, error)

	// BalanceInfoV2WithBodyWithResponse request with any body
	BalanceInfoV2WithBodyWithResponse(ctx context.Context, params *BalanceInfoV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BalanceInfoV2Response, error)

	BalanceInfoV2WithResponse(ctx context.Context, params *BalanceInfoV2Params, body BalanceInfoV2JSONRequestBody, reqEditors ...RequestEditorFn) (*BalanceInfoV2Response, error)

	// GetCallByIdV2WithBodyWithResponse request with any body
	GetCallByIdV2WithBodyWithResponse(ctx context.Context, params *GetCallByIdV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetCallByIdV2Response, error)

	GetCallByIdV2WithResponse(ctx context.Context, params *GetCallByIdV2Params, body GetCallByIdV2JSONRequestBody, reqEditors ...RequestEditorFn) (*GetCallByIdV2Response, error)

	// GetCallsByTimeV2WithBodyWithResponse request with any body
	GetCallsByTimeV2WithBodyWithResponse(ctx context.Context, params *GetCallsByTimeV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetCallsByTimeV2Response, error)

	GetCallsByTimeV2WithResponse(ctx context.Context, params *GetCallsByTimeV2Params, body GetCallsByTimeV2JSONRequestBody, reqEditors ...RequestEditorFn) (*GetCallsByTimeV2Response, error)

	// BalanceInfoV3WithBodyWithResponse request with any body
	BalanceInfoV3WithBodyWithResponse(ctx context.Context, params *BalanceInfoV3Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BalanceInfoV3Response, error)

	BalanceInfoV3WithResponse(ctx context.Context, params *BalanceInfoV3Params, body BalanceInfoV3JSONRequestBody, reqEditors ...RequestEditorFn) (*BalanceInfoV3Response, error)
}

type GetCallResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *NotFoundError
	JSON429      *TooManyRequestsError
	JSON500      *ServiceError
}

// Status returns HTTPResponse.Status
func (r GetCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ChatByActionIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Chat *OpenApiChatsComposition `json:"chat,omitempty"`
	}
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON429 *TooManyRequestsError
	JSON500 *N500
}

// Status returns HTTPResponse.Status
func (r ChatByActionIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChatByActionIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ChatsByTimeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Chats *[]OpenApiChatsComposition `json:"chats,omitempty"`
	}
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON429 *TooManyRequestsError
	JSON500 *N500
}

// Status returns HTTPResponse.Status
func (r ChatsByTimeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChatsByTimeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostCreateComplaintResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Error   *CpaError `json:"error,omitempty"`
		Success *bool     `json:"success,omitempty"`
	}
	JSON429 *TooManyRequestsError
}

// Status returns HTTPResponse.Status
func (r PostCreateComplaintResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCreateComplaintResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateComplaintByActionIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Error   *CpaError `json:"error,omitempty"`
		Success *bool     `json:"success,omitempty"`
	}
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON429 *TooManyRequestsError
	JSON500 *N500
}

// Status returns HTTPResponse.Status
func (r CreateComplaintByActionIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateComplaintByActionIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PhonesInfoFromChatsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Results []OpenAPIPhonesInfoFromChatsOut `json:"results"`

		// Total Число найденных чатов
		Total int `json:"total"`
	}
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON429 *TooManyRequestsError
	JSON500 *N500
}

// Status returns HTTPResponse.Status
func (r PhonesInfoFromChatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PhonesInfoFromChatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BalanceInfoV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Advance *int      `json:"advance,omitempty"`
		Balance *int      `json:"balance,omitempty"`
		Debt    *int      `json:"debt,omitempty"`
		Error   *CpaError `json:"error,omitempty"`
	}
	JSON429 *TooManyRequestsError
}

// Status returns HTTPResponse.Status
func (r BalanceInfoV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BalanceInfoV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCallByIdV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Calls *CallV2   `json:"calls,omitempty"`
		Error *CpaError `json:"error,omitempty"`
	}
	JSON429 *TooManyRequestsError
}

// Status returns HTTPResponse.Status
func (r GetCallByIdV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCallByIdV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCallsByTimeV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Calls *[]CallV2 `json:"calls,omitempty"`
		Error *CpaError `json:"error,omitempty"`
	}
	JSON429 *TooManyRequestsError
}

// Status returns HTTPResponse.Status
func (r GetCallsByTimeV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCallsByTimeV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BalanceInfoV3Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Balance *int `json:"balance,omitempty"`
	}
	JSON429 *TooManyRequestsError
}

// Status returns HTTPResponse.Status
func (r BalanceInfoV3Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BalanceInfoV3Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCallWithResponse request returning *GetCallResponse
func (c *ClientWithResponses) GetCallWithResponse(ctx context.Context, callId int64, params *GetCallParams, reqEditors ...RequestEditorFn) (*GetCallResponse, error) {
	rsp, err := c.GetCall(ctx, callId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCallResponse(rsp)
}

// ChatByActionIdWithResponse request returning *ChatByActionIdResponse
func (c *ClientWithResponses) ChatByActionIdWithResponse(ctx context.Context, actionId int, params *ChatByActionIdParams, reqEditors ...RequestEditorFn) (*ChatByActionIdResponse, error) {
	rsp, err := c.ChatByActionId(ctx, actionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChatByActionIdResponse(rsp)
}

// PostCreateComplaintWithBodyWithResponse request with arbitrary body returning *PostCreateComplaintResponse
func (c *ClientWithResponses) PostCreateComplaintWithBodyWithResponse(ctx context.Context, params *PostCreateComplaintParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateComplaintResponse, error) {
	rsp, err := c.PostCreateComplaintWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateComplaintResponse(rsp)
}

func (c *ClientWithResponses) PostCreateComplaintWithResponse(ctx context.Context, params *PostCreateComplaintParams, body PostCreateComplaintJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateComplaintResponse, error) {
	rsp, err := c.PostCreateComplaint(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateComplaintResponse(rsp)
}

// CreateComplaintByActionIdWithBodyWithResponse request with arbitrary body returning *CreateComplaintByActionIdResponse
func (c *ClientWithResponses) CreateComplaintByActionIdWithBodyWithResponse(ctx context.Context, params *CreateComplaintByActionIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateComplaintByActionIdResponse, error) {
	rsp, err := c.CreateComplaintByActionIdWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateComplaintByActionIdResponse(rsp)
}

func (c *ClientWithResponses) CreateComplaintByActionIdWithResponse(ctx context.Context, params *CreateComplaintByActionIdParams, body CreateComplaintByActionIdJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateComplaintByActionIdResponse, error) {
	rsp, err := c.CreateComplaintByActionId(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateComplaintByActionIdResponse(rsp)
}

// PhonesInfoFromChatsWithBodyWithResponse request with arbitrary body returning *PhonesInfoFromChatsResponse
func (c *ClientWithResponses) PhonesInfoFromChatsWithBodyWithResponse(ctx context.Context, params *PhonesInfoFromChatsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PhonesInfoFromChatsResponse, error) {
	rsp, err := c.PhonesInfoFromChatsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePhonesInfoFromChatsResponse(rsp)
}

func (c *ClientWithResponses) PhonesInfoFromChatsWithResponse(ctx context.Context, params *PhonesInfoFromChatsParams, body PhonesInfoFromChatsJSONRequestBody, reqEditors ...RequestEditorFn) (*PhonesInfoFromChatsResponse, error) {
	rsp, err := c.PhonesInfoFromChats(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePhonesInfoFromChatsResponse(rsp)
}

// BalanceInfoV2WithBodyWithResponse request with arbitrary body returning *BalanceInfoV2Response
func (c *ClientWithResponses) BalanceInfoV2WithBodyWithResponse(ctx context.Context, params *BalanceInfoV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BalanceInfoV2Response, error) {
	rsp, err := c.BalanceInfoV2WithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBalanceInfoV2Response(rsp)
}

func (c *ClientWithResponses) BalanceInfoV2WithResponse(ctx context.Context, params *BalanceInfoV2Params, body BalanceInfoV2JSONRequestBody, reqEditors ...RequestEditorFn) (*BalanceInfoV2Response, error) {
	rsp, err := c.BalanceInfoV2(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBalanceInfoV2Response(rsp)
}

// GetCallByIdV2WithBodyWithResponse request with arbitrary body returning *GetCallByIdV2Response
func (c *ClientWithResponses) GetCallByIdV2WithBodyWithResponse(ctx context.Context, params *GetCallByIdV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetCallByIdV2Response, error) {
	rsp, err := c.GetCallByIdV2WithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCallByIdV2Response(rsp)
}

func (c *ClientWithResponses) GetCallByIdV2WithResponse(ctx context.Context, params *GetCallByIdV2Params, body GetCallByIdV2JSONRequestBody, reqEditors ...RequestEditorFn) (*GetCallByIdV2Response, error) {
	rsp, err := c.GetCallByIdV2(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCallByIdV2Response(rsp)
}

// GetCallsByTimeV2WithBodyWithResponse request with arbitrary body returning *GetCallsByTimeV2Response
func (c *ClientWithResponses) GetCallsByTimeV2WithBodyWithResponse(ctx context.Context, params *GetCallsByTimeV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetCallsByTimeV2Response, error) {
	rsp, err := c.GetCallsByTimeV2WithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCallsByTimeV2Response(rsp)
}

func (c *ClientWithResponses) GetCallsByTimeV2WithResponse(ctx context.Context, params *GetCallsByTimeV2Params, body GetCallsByTimeV2JSONRequestBody, reqEditors ...RequestEditorFn) (*GetCallsByTimeV2Response, error) {
	rsp, err := c.GetCallsByTimeV2(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCallsByTimeV2Response(rsp)
}

// ChatsByTimeWithBodyWithResponse request with arbitrary body returning *ChatsByTimeResponse
func (c *ClientWithResponses) ChatsByTimeWithBodyWithResponse(ctx context.Context, params *ChatsByTimeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChatsByTimeResponse, error) {
	rsp, err := c.ChatsByTimeWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChatsByTimeResponse(rsp)
}

func (c *ClientWithResponses) ChatsByTimeWithResponse(ctx context.Context, params *ChatsByTimeParams, body ChatsByTimeJSONRequestBody, reqEditors ...RequestEditorFn) (*ChatsByTimeResponse, error) {
	rsp, err := c.ChatsByTime(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChatsByTimeResponse(rsp)
}

// BalanceInfoV3WithBodyWithResponse request with arbitrary body returning *BalanceInfoV3Response
func (c *ClientWithResponses) BalanceInfoV3WithBodyWithResponse(ctx context.Context, params *BalanceInfoV3Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BalanceInfoV3Response, error) {
	rsp, err := c.BalanceInfoV3WithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBalanceInfoV3Response(rsp)
}

func (c *ClientWithResponses) BalanceInfoV3WithResponse(ctx context.Context, params *BalanceInfoV3Params, body BalanceInfoV3JSONRequestBody, reqEditors ...RequestEditorFn) (*BalanceInfoV3Response, error) {
	rsp, err := c.BalanceInfoV3(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBalanceInfoV3Response(rsp)
}

// ParseGetCallResponse parses an HTTP response from a GetCallWithResponse call
func ParseGetCallResponse(rsp *http.Response) (*GetCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseChatByActionIdResponse parses an HTTP response from a ChatByActionIdWithResponse call
func ParseChatByActionIdResponse(rsp *http.Response) (*ChatByActionIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChatByActionIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Chat *OpenApiChatsComposition `json:"chat,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseChatsByTimeResponse parses an HTTP response from a ChatsByTimeWithResponse call
func ParseChatsByTimeResponse(rsp *http.Response) (*ChatsByTimeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChatsByTimeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Chats *[]OpenApiChatsComposition `json:"chats,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostCreateComplaintResponse parses an HTTP response from a PostCreateComplaintWithResponse call
func ParsePostCreateComplaintResponse(rsp *http.Response) (*PostCreateComplaintResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCreateComplaintResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Error   *CpaError `json:"error,omitempty"`
			Success *bool     `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseCreateComplaintByActionIdResponse parses an HTTP response from a CreateComplaintByActionIdWithResponse call
func ParseCreateComplaintByActionIdResponse(rsp *http.Response) (*CreateComplaintByActionIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateComplaintByActionIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Error   *CpaError `json:"error,omitempty"`
			Success *bool     `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePhonesInfoFromChatsResponse parses an HTTP response from a PhonesInfoFromChatsWithResponse call
func ParsePhonesInfoFromChatsResponse(rsp *http.Response) (*PhonesInfoFromChatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PhonesInfoFromChatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Results []OpenAPIPhonesInfoFromChatsOut `json:"results"`

			// Total Число найденных чатов
			Total int `json:"total"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseBalanceInfoV2Response parses an HTTP response from a BalanceInfoV2WithResponse call
func ParseBalanceInfoV2Response(rsp *http.Response) (*BalanceInfoV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BalanceInfoV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Advance *int      `json:"advance,omitempty"`
			Balance *int      `json:"balance,omitempty"`
			Debt    *int      `json:"debt,omitempty"`
			Error   *CpaError `json:"error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseGetCallByIdV2Response parses an HTTP response from a GetCallByIdV2WithResponse call
func ParseGetCallByIdV2Response(rsp *http.Response) (*GetCallByIdV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCallByIdV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Calls *CallV2   `json:"calls,omitempty"`
			Error *CpaError `json:"error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseGetCallsByTimeV2Response parses an HTTP response from a GetCallsByTimeV2WithResponse call
func ParseGetCallsByTimeV2Response(rsp *http.Response) (*GetCallsByTimeV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCallsByTimeV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Calls *[]CallV2 `json:"calls,omitempty"`
			Error *CpaError `json:"error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseBalanceInfoV3Response parses an HTTP response from a BalanceInfoV3WithResponse call
func ParseBalanceInfoV3Response(rsp *http.Response) (*BalanceInfoV3Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BalanceInfoV3Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Balance *int `json:"balance,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequestsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}
