// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// GetTokenOAuthRequest defines model for GetTokenOAuthRequest.
type GetTokenOAuthRequest struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Code         string `json:"code"`
	GrantType    string `json:"grant_type"`
}

// GetTokenRequest defines model for GetTokenRequest.
type GetTokenRequest struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	GrantType    string `json:"grant_type"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`

	// GrantType Тип OAuth flow. Строка refresh_token
	GrantType    string `json:"grant_type"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessTokenFormdataRequestBody defines body for GetAccessToken for application/x-www-form-urlencoded ContentType.
type GetAccessTokenFormdataRequestBody = GetTokenRequest

// GetAccessTokenAuthorizationCodeFormdataRequestBody defines body for GetAccessTokenAuthorizationCode for application/x-www-form-urlencoded ContentType.
type GetAccessTokenAuthorizationCodeFormdataRequestBody = GetTokenOAuthRequest

// RefreshAccessTokenAuthorizationCodeFormdataRequestBody defines body for RefreshAccessTokenAuthorizationCode for application/x-www-form-urlencoded ContentType.
type RefreshAccessTokenAuthorizationCodeFormdataRequestBody = RefreshRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAccessTokenWithBody request with any body
	GetAccessTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetAccessTokenWithFormdataBody(ctx context.Context, body GetAccessTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccessTokenAuthorizationCodeWithBody request with any body
	GetAccessTokenAuthorizationCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetAccessTokenAuthorizationCodeWithFormdataBody(ctx context.Context, body GetAccessTokenAuthorizationCodeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RefreshAccessTokenAuthorizationCodeWithBody request with any body
	RefreshAccessTokenAuthorizationCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RefreshAccessTokenAuthorizationCodeWithFormdataBody(ctx context.Context, body RefreshAccessTokenAuthorizationCodeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAccessTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccessTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAccessTokenWithFormdataBody(ctx context.Context, body GetAccessTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccessTokenRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAccessTokenAuthorizationCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccessTokenAuthorizationCodeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAccessTokenAuthorizationCodeWithFormdataBody(ctx context.Context, body GetAccessTokenAuthorizationCodeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccessTokenAuthorizationCodeRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RefreshAccessTokenAuthorizationCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshAccessTokenAuthorizationCodeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RefreshAccessTokenAuthorizationCodeWithFormdataBody(ctx context.Context, body RefreshAccessTokenAuthorizationCodeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshAccessTokenAuthorizationCodeRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAccessTokenRequestWithFormdataBody calls the generic GetAccessToken builder with application/x-www-form-urlencoded body
func NewGetAccessTokenRequestWithFormdataBody(server string, body GetAccessTokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewGetAccessTokenRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewGetAccessTokenRequestWithBody generates requests for GetAccessToken with any type of body
func NewGetAccessTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAccessTokenAuthorizationCodeRequestWithFormdataBody calls the generic GetAccessTokenAuthorizationCode builder with application/x-www-form-urlencoded body
func NewGetAccessTokenAuthorizationCodeRequestWithFormdataBody(server string, body GetAccessTokenAuthorizationCodeFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewGetAccessTokenAuthorizationCodeRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewGetAccessTokenAuthorizationCodeRequestWithBody generates requests for GetAccessTokenAuthorizationCode with any type of body
func NewGetAccessTokenAuthorizationCodeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/token‎")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRefreshAccessTokenAuthorizationCodeRequestWithFormdataBody calls the generic RefreshAccessTokenAuthorizationCode builder with application/x-www-form-urlencoded body
func NewRefreshAccessTokenAuthorizationCodeRequestWithFormdataBody(server string, body RefreshAccessTokenAuthorizationCodeFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewRefreshAccessTokenAuthorizationCodeRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewRefreshAccessTokenAuthorizationCodeRequestWithBody generates requests for RefreshAccessTokenAuthorizationCode with any type of body
func NewRefreshAccessTokenAuthorizationCodeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/token‎‎")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAccessTokenWithBodyWithResponse request with any body
	GetAccessTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetAccessTokenResponse, error)

	GetAccessTokenWithFormdataBodyWithResponse(ctx context.Context, body GetAccessTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*GetAccessTokenResponse, error)

	// GetAccessTokenAuthorizationCodeWithBodyWithResponse request with any body
	GetAccessTokenAuthorizationCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetAccessTokenAuthorizationCodeResponse, error)

	GetAccessTokenAuthorizationCodeWithFormdataBodyWithResponse(ctx context.Context, body GetAccessTokenAuthorizationCodeFormdataRequestBody, reqEditors ...RequestEditorFn) (*GetAccessTokenAuthorizationCodeResponse, error)

	// RefreshAccessTokenAuthorizationCodeWithBodyWithResponse request with any body
	RefreshAccessTokenAuthorizationCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RefreshAccessTokenAuthorizationCodeResponse, error)

	RefreshAccessTokenAuthorizationCodeWithFormdataBodyWithResponse(ctx context.Context, body RefreshAccessTokenAuthorizationCodeFormdataRequestBody, reqEditors ...RequestEditorFn) (*RefreshAccessTokenAuthorizationCodeResponse, error)
}

type GetAccessTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// AccessToken Ключ для временной авторизации в системе
		AccessToken *string `json:"access_token,omitempty"`

		// ExpiresIn Время жизни ключа в секундах
		ExpiresIn *float32 `json:"expires_in,omitempty"`

		// TokenType Тип ключа авторизации
		TokenType *string `json:"token_type,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetAccessTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccessTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAccessTokenAuthorizationCodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// AccessToken Ключ для временной авторизации в системе
		AccessToken *string `json:"access_token,omitempty"`

		// ExpiresIn Время жизни ключа в секундах
		ExpiresIn *float32 `json:"expires_in,omitempty"`

		// RefreshToken Ключ для обновления токена доступа
		RefreshToken *string `json:"refresh_token,omitempty"`

		// Scope Полученный скоуп
		Scope *string `json:"scope,omitempty"`

		// TokenType Тип ключа авторизации
		TokenType *string `json:"token_type,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetAccessTokenAuthorizationCodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccessTokenAuthorizationCodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RefreshAccessTokenAuthorizationCodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// AccessToken Новый ключ для временной авторизации в системе
		AccessToken *string `json:"access_token,omitempty"`

		// ExpiresIn Время жизни ключа в секундах
		ExpiresIn *float32 `json:"expires_in,omitempty"`

		// RefreshToken Новый ключ для обновления токена доступа
		RefreshToken *string `json:"refresh_token,omitempty"`

		// Scope Полученный скоуп
		Scope *string `json:"scope,omitempty"`

		// TokenType Тип ключа авторизации
		TokenType *string `json:"token_type,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RefreshAccessTokenAuthorizationCodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RefreshAccessTokenAuthorizationCodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAccessTokenWithBodyWithResponse request with arbitrary body returning *GetAccessTokenResponse
func (c *ClientWithResponses) GetAccessTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetAccessTokenResponse, error) {
	rsp, err := c.GetAccessTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccessTokenResponse(rsp)
}

func (c *ClientWithResponses) GetAccessTokenWithFormdataBodyWithResponse(ctx context.Context, body GetAccessTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*GetAccessTokenResponse, error) {
	rsp, err := c.GetAccessTokenWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccessTokenResponse(rsp)
}

// GetAccessTokenAuthorizationCodeWithBodyWithResponse request with arbitrary body returning *GetAccessTokenAuthorizationCodeResponse
func (c *ClientWithResponses) GetAccessTokenAuthorizationCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetAccessTokenAuthorizationCodeResponse, error) {
	rsp, err := c.GetAccessTokenAuthorizationCodeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccessTokenAuthorizationCodeResponse(rsp)
}

func (c *ClientWithResponses) GetAccessTokenAuthorizationCodeWithFormdataBodyWithResponse(ctx context.Context, body GetAccessTokenAuthorizationCodeFormdataRequestBody, reqEditors ...RequestEditorFn) (*GetAccessTokenAuthorizationCodeResponse, error) {
	rsp, err := c.GetAccessTokenAuthorizationCodeWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccessTokenAuthorizationCodeResponse(rsp)
}

// RefreshAccessTokenAuthorizationCodeWithBodyWithResponse request with arbitrary body returning *RefreshAccessTokenAuthorizationCodeResponse
func (c *ClientWithResponses) RefreshAccessTokenAuthorizationCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RefreshAccessTokenAuthorizationCodeResponse, error) {
	rsp, err := c.RefreshAccessTokenAuthorizationCodeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshAccessTokenAuthorizationCodeResponse(rsp)
}

func (c *ClientWithResponses) RefreshAccessTokenAuthorizationCodeWithFormdataBodyWithResponse(ctx context.Context, body RefreshAccessTokenAuthorizationCodeFormdataRequestBody, reqEditors ...RequestEditorFn) (*RefreshAccessTokenAuthorizationCodeResponse, error) {
	rsp, err := c.RefreshAccessTokenAuthorizationCodeWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshAccessTokenAuthorizationCodeResponse(rsp)
}

// ParseGetAccessTokenResponse parses an HTTP response from a GetAccessTokenWithResponse call
func ParseGetAccessTokenResponse(rsp *http.Response) (*GetAccessTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccessTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// AccessToken Ключ для временной авторизации в системе
			AccessToken *string `json:"access_token,omitempty"`

			// ExpiresIn Время жизни ключа в секундах
			ExpiresIn *float32 `json:"expires_in,omitempty"`

			// TokenType Тип ключа авторизации
			TokenType *string `json:"token_type,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAccessTokenAuthorizationCodeResponse parses an HTTP response from a GetAccessTokenAuthorizationCodeWithResponse call
func ParseGetAccessTokenAuthorizationCodeResponse(rsp *http.Response) (*GetAccessTokenAuthorizationCodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccessTokenAuthorizationCodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// AccessToken Ключ для временной авторизации в системе
			AccessToken *string `json:"access_token,omitempty"`

			// ExpiresIn Время жизни ключа в секундах
			ExpiresIn *float32 `json:"expires_in,omitempty"`

			// RefreshToken Ключ для обновления токена доступа
			RefreshToken *string `json:"refresh_token,omitempty"`

			// Scope Полученный скоуп
			Scope *string `json:"scope,omitempty"`

			// TokenType Тип ключа авторизации
			TokenType *string `json:"token_type,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRefreshAccessTokenAuthorizationCodeResponse parses an HTTP response from a RefreshAccessTokenAuthorizationCodeWithResponse call
func ParseRefreshAccessTokenAuthorizationCodeResponse(rsp *http.Response) (*RefreshAccessTokenAuthorizationCodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RefreshAccessTokenAuthorizationCodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// AccessToken Новый ключ для временной авторизации в системе
			AccessToken *string `json:"access_token,omitempty"`

			// ExpiresIn Время жизни ключа в секундах
			ExpiresIn *float32 `json:"expires_in,omitempty"`

			// RefreshToken Новый ключ для обновления токена доступа
			RefreshToken *string `json:"refresh_token,omitempty"`

			// Scope Полученный скоуп
			Scope *string `json:"scope,omitempty"`

			// TokenType Тип ключа авторизации
			TokenType *string `json:"token_type,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb/W4bV3Z/lYtxAVsCSSmyk+4SCLZarbN2G9i7kgIUtQxpTI4lJhSHmRlaUQ0BIhlH",
	"2cq1Um8KBEWzSbp/tP8UGFEaaySR1Cvc+wr7JMU55873HZLyR2J0kwCWRHLOPfd8/M4nH2sVc7NpNoyG",
	"Y2vlx5pd2TA2dfz1t4azbH5iNO7Ot5yNRePTlmE78HrTMpuG5dQM/FSlXjMazmqtCn84201DK2u2Y9Ua",
	"69pOIXjXNiqW4ag/YVYN5Rvrlt5wVunlx1rVeKi36o5W1vSWs2FatX/WnZrZWMXHC+mndwqaZXzaqllG",
	"VSvfi5MqxBhOsyeZuR+SMx98bFQcYCaQxRsTQ95t5ZMVy6gaDaem1+3XdVvVNReNh5Zhb/zot7To3FUH",
	"ZKwVtKphV6xaEzSslTX+X9znFwztkD2sm1slxn8QHbHLh/yMuyz9dObY5AeyjL2suSTpZgW6U9Bso9Ky",
	"as72EvgVCXE+bsAL0vxTN/5f0eFDNv+724z7os0v+JCfi6f8RHS5JzpSFHNMtBnvc0884S4fcJ+f8D4f",
	"8j7L+kiJ8W9ShE5Fh3uMe/yIDxk/5ufiAH4MRVt0RJdfcJfxM3gFaA/EPu8zfix2RZcfcV88YRExPuQ9",
	"7gI5fs49fsr4hdjlPhO73OUn+O8hH4oOP+MeA/J8iMob8EFwPD7Az/mQv+Ae3EUclNg9/h0fwpl8yA/x",
	"s979a1ccfX1mvtms1yp4vflKxbDtKa2ggWmghHWVhBMvfmTVtbK24ThNuzwzoz+qOWbJas2Y8CGtoNkV",
	"s2kEpMy6qVfLltE0LcBIDZk6F12xR5yCEIeiA3/CzXiP8a94D3894S4/QpGd8DPuawWt5hibdllvNuvb",
	"q490IodX7yOxkOAxH5J8URYoWfEUtCCeMNEVbWCAH4UEa42HZg5rPh+Iz1Hgfe6KL7jPfQbyxH/Ev4gD",
	"3kOtoczFE62gfWw+QA6lgO3LE0ZVn3Mf3BMsZQC21OMu/M0Hog2flQdVHl2CvNjlHj8Rz0Ba8vlHekVv",
	"VLaByPehnbnoGYkDxQHvh4duWTUHHJV/gy6TkHxGKmDPPe6JXdGhG8HNWPw0raBtGrZtNNYNq2wZehVI",
	"/zdqjYiKNh8i4T/ESJLrtkUbXzsGw4f7ofWgzocJuiHP/wk+wX3xOfdBLOgdPQkAr3KUvWFazqpjWJur",
	"ltFwwou8uk0xfgYggFYB8LLLh2KPD/gQmHNRqQN+LPYVTFxaU5Of5OiOPeKSiFNAycffQPO+8kytoLXs",
	"mOInllcugkqKqw/0ut6oGKMoH6I5ko27OQTFQUAQYjn59EhuQ4iWer1AcyHGT/MP2SloGAlT4NqslUKA",
	"pUgJgTEIlYC4c/DoAgbXhVii89rDYjaZevmw2EN472PAGsh3D3gf/A/ewih4zv3Q+kjEohMYI4SGC7yF",
	"PzLQZaNbRSWoMGK9ihLgJYokUBY0HL2CaZyxqdeAmN1qQgwMQuLfBQRBeylFqayKycsNY87jMe5SrERr",
	"O5FGNqSMA2JdB5M8j54L9YEWiVA3AAeA0Ch9XEHNx8Nz3skkHvx0pTE9HSEjmZs89xAfHgCYorshokjj",
	"gBPgU6Bl0RYHBMVH4J6iDfyxe/zPELlRAhiQUmYcAbk4uH8t0N3W1laku7qxrtdnmpa56phm3Z5pth7U",
	"a5Wi3qxNlaanGWNsBVPgmlNH2Pwqe2uEg0eGZZOu3gH1mU2joTdrWlm7XpotzWoFrak7G2hZM2HW3DSp",
	"JhitaxBTD+VCcD1AIQwZZATimdgDuUlpKlWiITcEU7cBon5rOOQFyzK/t6g8+bVZ3Q4s1WggZ7GsZeaz",
	"4tbWVvGhaW0WW1bdaEAWXI1KXPjtbyzjoVbWrsxENfCMLIBn0hXfzg6VCXbTbNiUG87Nzo44/2PbRKkZ",
	"n+mbzTqloHiNoAzRPlnY+NT5pbH1+zvzla31B7eaN7Y/qL6rFTTjs2bNMuzVWkMr/+K9G7Oz0qdl5aT9",
	"2tAtwwK9RXdJFmrJkzIq+w9SRaiItL7yHanHMJlqI+hTFpYpt+LsZ45+TkfBqS+kM/kJ28ATPH4mupiq",
	"uJiSghp1qBRrDef6XHRoo7X5gCQRF9BjdQEZPyXP9LKVYbqmy4Ldn9GHPfElVkmnlP9CxtihErC1ualb",
	"22pYJEWxsHTV120oQcngtfvwPDngX3af/Xg+KMMTpk8IdEPRoXD2xegsY5TnZuveH9mVE42sn9ifUy0J",
	"LXgm+JlLCwO9Vk4VHIV0nfAzYoxFjExXaMyVM9kLhPgoPXFTWaLqnlJ5Y9yXUES0sYbp8gsVpf9ncJdu",
	"56SQbzT4/UmVVr4F8Ce7qW8DBKYau28A/N6tfrB9o3nrwfpWZf7O77eMXzqfbix8Mhn4qZ8N/g5+/nTg",
	"9y0ommz97K8PB0fc/mdIvCwkqrDqMqCIIwULqjetfO+x1sqv8rWd+yGtjDi+Rv1FnXmxz0SbKl3AurCJ",
	"gagZAt+Ae9gAe0IdSN6PeligKF90xNOY/vNc4S+7X5OEjqO2NghNGtUZd/kLbICP7JrIrnJYp5dWGvA/",
	"Y++UWMx6XPAZNj0dznGmpxn3oxdomAMv9ti9WMemT4xAwT9ADrycirxpmQ8NG4ppvW6DCqaAibkS48/F",
	"PjEr9rGu96g95PFD7sXEVIbPM8bW1tbkb5WWVWfFD1nxH9nv7i4ts6v5bZyZq2xlRT4G/xVvsasLhOHF",
	"5e2mUWZjo0iaQrGqO3r0PrsazcPez3bQxj4dCv79ldbs7PXKwoe3b95ZXr39G/zTmPR50lOSxtLNhcWb",
	"y5JOUorXS4x/jb1Rj7KB/WCcIg5QEfEQL/YZP0PrF2164wg/C256hrawlojcZUYhhRE38wsLN5eWVpfv",
	"/sPNO8TMGlliHLLB1k8R/XsKmBzyI3TGAdofdrtYkc3dYGDBmINQT3NIoQZHHOHoLF37lfDs7zB5OQdT",
	"+1c8DD8Mdtif0JMJqAh5Q25L2F9q6JsAiRKXCtpnxWrNbtb17Tv0Bv9O0aBzcxIubB1fBqIUPbsJczSG",
	"YxC8nKqB+3QknCEU4QSKJcyBQSaX6TgzaV30PJiTSw3qOTRNvFxcMbKpyXuiK54xnFvQaceoCtElPtE+",
	"8fUjyiZAFsEMSF4hIx6PwDKAkarxyKhD/mNHaBIf+JUS1tONghthcvLwKMHhrvgSjlKen5BrnvRjo2K6",
	"S6DxqBs7oZ6vYYsWB3UXwVX4cTgQE/uYILWBFkiGNBENrOG2kvUpDCzZBj0NvBSGID6Hu4tuvgGw6OLE",
	"HgpFXvke5nHBn+mwU62t1xy9blYMvVGqmJuQ7G+2GjVne8ZpOaYFkExj7OJc0WpNgSqRiy9oAJhxKLy5",
	"D5EpZLunkrkMjW7U3e5I0Z/BJ0AkJ+jje8l5Ne+DDo4xhLrYHu9jCvBHhuJ9IW2DiS8RdhGdhjLGu5BD",
	"XCTYx1EakD+KTA8VdOXKFcb/B2iwd8qMf5+1UZwbZNcMULvfp/1JdClKqGw5hgMTelTk8Tm+E7m36GLe",
	"cULqLwN304x/Q0FEwX6BYU4crFR4jB+KLsmb7Lwnx8Ud8RT1lucycNseC8eU0mWPZSK7iylZ2Fy8QDPq",
	"AW+LRrVmGRWHfbR4mxUB4I/RgdoFmaGF7AU5vMtPgbnIvnBQ6yGXu1jAdAgkckE8dOlJmeQ/BJWD2C8k",
	"WfIU0RASAglnvB94clLwz9g1eXYSE5IljxxihXVLsA6Bhj+FnP0pMnaJlFklg1xj2fEZ7t+ATwT7Nj3g",
	"+IImwYH50hxTMWCiKBFjM73ngy7xPP7SaSL5YCihbBCSTpNEhmM81JOz9wFJXHVHQvYBil3uF7m4dDHA",
	"p4e8R0gcUyVChbQdNA3xDO2GFM9dlQl6YyKVaEt0Bg9CH22LtkwH9mNBNmWCKgPMGznm7E31ESYSxkP8",
	"hPctg8Ukmx9l9jo2TZJ0sYtSZm9m0wSOymw3lNnLLzcAwXCpp8xe005PQLXySM3buPWk4Hm5n1Rmk6wn",
	"BQ/Fk7HJj7/E8lWohNRGSM5hL7cQEhwyivLlFmOAYnojT014soU8oBct0F1a0qpdp4hkuORXZq+y4wcE",
	"VatZr4XbSfelVExc1t8ucVK4mqW85MSbWYmscK7M+A/YiznHrWFwwTMEOGz2KLFaxhtKaxGL8oz92fhl",
	"kMTZVI9AqYfwKWtzH0Iu5nzYxlDvp/4q6NvLloxZNVZas7Nz743ptNCHsN/6/ugGujw+Ib7roSrSV3+a",
	"Ep5cxlIF17CSUlIhVPGCNExmgHHJeemmXwFsp0vxDw0iDFXEhcx4cRtZ1fQgAypQUd2RKX8mo3SjbBqq",
	"xj3ICBU5I+YslHqMTx/TRcuNECVyC2fJBhrtKIP991jlq5Y03OQQAzrRXEkvCo3uJqxohUR5eBGmd26Y",
	"e0nbz2UC0xqf5iVHMq28xg8RIwCdPbE7RfqHukJ9RJhpXYsXIVOFdM3BD8F+qLN3TFVlWPS7QDq3LlPm",
	"qT5B92Hynj0W22ZHRHMxF+qIXbYGTrpWYvxbyT7GArFbYLE2RbAyr26uYOaPIY16iF6y8JJXjKpHar/L",
	"UoytBVAiB3jUOtDr9Qd65RPCl7UCI232qZbIytsPvENZkw1UyJV/3K9AJBKo5j9avnV38fY/zS/fvntn",
	"deHub25KxFLg0Lt5fhL0c7F8oH47JPCxaURiFkVQ9BoIMdHN9EsuAJPEv2EvQ3RCAZ7l7SEOk0NqQBSX",
	"lhbT4IZWEH/kVB3zr+FxcthFu4geRmA1NIuDKbTOoCEjG49hIKN7xywXBxPF9Jw83M5MbyPFR1yRlbzl",
	"w47st2jemmHHWDrjneuqyrvemzQKjfarMAIpu/1BT+9LTKiS/eUC+RK1h3vohX8Y64HXgEwHK5wXidHa",
	"yw6qWTH4UhmZLDjHc4Tep7HZLjqV2JWJgstifQOMsEcYHLAVh63sRM7nU6PzkFrOkINGfvGYdLuS2EtY",
	"0cpsRcubOK1oheChaIkAHqGVi+C9xKw/TnHx5geLN5du5ZDEpJE+PiZzjJ6JxvH0II3MVrSVxk5oeUpb",
	"E20+FE9oHCaDa1wOgIuJa6Qzqb/Ns2HsEQVZlHL8V0num/dVth2bKioHHSkjCKeOlE298aljTBC/yBNE",
	"zBsUAqbuX/7kMo7lr3ty+SbHllR6BE07uYkTi1FUlGJ9NmZam/o2SA9wYIRq5W1zVv2p6MCmPQT7DPbR",
	"nWTSP8Sc5BAziRuz10uM/xA5S2xTJoFeCZs8FPtEUcnOiBAuLYYUMlIe2Mcdl+YksZPU84r5RyHzraBY",
	"dZ2SyMvFhQCiXzJpeaV8ZWSqkgDEUc9MnKC8htwkSyLB5vu5kSdKTfjzeLydZLKMRrdHozRKCTBHBrP6",
	"+6W7dwpygsKikguNQDawGPKJmo/DnJyi+gEm9RNTtoSvIEhlhqMBIMVxFocTQ0adieADycjGYvtiPs1z",
	"sO5k4aw1WvdPfPPsEJMKLzbCEU+iOPl1XuORmrnJ2tV2dMeQke88cA/04D389RDA7gSxyqfBHU2X3Ni0",
	"J/+L4lhsYmeQn5LkcAIYhAvARALI3DmWkt8So+8KknqSH0AyJyirsHhP8U9tI3h6YWnxgyKyHBhNDwGB",
	"kCnUDOV3Q9knPwiXkGUTKO8r7rKdlRitJZqNyiaP3G9LTB5lC2uPhEXjZMJMlXgKyQ0E2YyN7SAA4IlO",
	"tHoApdAsVvFVs2LPNC3TMStmsGowJzcOkLbcl0gaSyFhLXm6xOdpNyAIpB2K/kEp6ye+nNmLSSs04I8W",
	"P3wLOqj0SbiPJLW0PL+cbmsAuvlSRJ68fQxYcMB2LLuQbmSXOKX3E9987Ce6QerJ+yt27C47dk+Fzp+b",
	"X5dtfk1mQt+SNuSqGI295XeYxZ7oQnIqs9g4znsphO7JuSGYShDhaByBb0ZhLwUn3Csx/keKneEOgDy9",
	"iyh4FrNSxdcyvFQoi/wg3kNXRX4/uYmYWZZWLCV+pe5GBClvdqtQ27m/838BAAD//8K8pOoiSQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
